-- WorldCons D1 schema: worldcons_search
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists search_documents (
  article_id text not null,
  jurisdiction text,
  source_key text,
  language text,
  content_type text,
  publication_state text,
  review_state text,
  original_published_at text,
  display_title text,
  case_numbers text,
  search_text text,
  tags_text text,
  projection_version integer not null default 1,
  checksum text,
  updated_at text not null,
  primary key (article_id)
);

create virtual table if not exists search_fts using fts5(article_id UNINDEXED, title, case_numbers, search_text, tags_text);
