-- WorldCons D1 schema: worldcons_ingest
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists article_raw_externalization_ledger (
  id text not null,
  article_table text not null check (article_table in ('articles', 'article_content_versions_p3')),
  article_row_id text not null,
  article_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  actor_type text not null check (actor_type in ('service', 'operator')),
  actor_id text,
  externalized_at text not null,
  primary key (id)
);
create index if not exists article_raw_externalization_ledger_article_idx on article_raw_externalization_ledger (article_id, externalized_at);
create unique index if not exists article_raw_externalization_ledger_unique_idx on article_raw_externalization_ledger (article_table, article_row_id, externalization_contract_version);

create table if not exists article_raw_externalization_permits (
  article_table text not null,
  article_row_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (article_table, article_row_id)
);

create table if not exists article_raw_inline_clear_permits (
  article_table text not null,
  article_row_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (article_table, article_row_id)
);

create table if not exists article_raw_inline_restore_permits (
  article_table text not null,
  article_row_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (article_table, article_row_id)
);

create table if not exists ingestion_runs (
  id text not null,
  source_key text not null,
  started_at text not null,
  finished_at text,
  status text not null,
  discovered_count integer not null default 0,
  fetched_count integer not null default 0,
  summarized_count integer not null default 0,
  failed_count integer not null default 0,
  error_message text,
  metadata text,
  primary key (id)
);

create table if not exists source_artifact_externalization_ledger (
  id text not null,
  artifact_table text not null check (artifact_table in ('source_fetch_artifacts', 'source_normalization_artifacts')),
  artifact_id text not null,
  item_id text,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  actor_type text not null check (actor_type in ('service', 'operator')),
  actor_id text,
  externalized_at text not null,
  primary key (id)
);
create index if not exists source_artifact_externalization_ledger_item_idx on source_artifact_externalization_ledger (item_id, externalized_at);
create unique index if not exists source_artifact_externalization_ledger_unique_idx on source_artifact_externalization_ledger (artifact_table, artifact_id, externalization_contract_version);

create table if not exists source_artifact_externalization_permits (
  artifact_table text not null check (artifact_table in ('source_fetch_artifacts', 'source_normalization_artifacts')),
  artifact_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (artifact_table, artifact_id)
);

create table if not exists source_artifact_inline_clear_permits (
  artifact_table text not null check (artifact_table in ('source_fetch_artifacts', 'source_normalization_artifacts')),
  artifact_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (artifact_table, artifact_id)
);

create table if not exists source_artifact_inline_restore_permits (
  artifact_table text not null check (artifact_table in ('source_fetch_artifacts', 'source_normalization_artifacts')),
  artifact_id text not null,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size text not null,
  externalization_contract_version text not null,
  created_at text not null,
  primary key (artifact_table, artifact_id)
);

create table if not exists source_backfill_item_events (
  id text not null,
  item_id text not null,
  attempt_id text,
  event_type text not null check (event_type in ('item_discovered', 'item_claimed', 'item_lease_extended', 'fetch_recorded', 'normalization_recorded', 'item_completed', 'item_failed', 'claim_released', 'verification_noop', 'item_excluded')),
  phase text,
  safe_details text not null default '{}',
  occurred_at text not null,
  primary key (id)
);
create index if not exists source_backfill_item_events_item_idx on source_backfill_item_events (item_id, occurred_at, id);

create table if not exists source_backfill_items (
  id text not null,
  snapshot_id text not null,
  source_key text not null,
  stable_item_key text not null,
  source_record_id text,
  discovered_url text not null,
  authority_url text,
  document_type text,
  discovered_decision_date_hint text,
  status text not null default 'discovered' check (status in ('discovered', 'queued', 'fetching', 'fetched', 'normalized', 'verified', 'published', 'retry_wait', 'terminal_failure', 'waived_failure', 'excluded', 'duplicate', 'withdrawn')),
  attempt_count integer not null default 0,
  next_attempt_at text,
  retry_phase text,
  claimed_attempt_id text,
  claimed_fencing_token text,
  claimed_phase text,
  lease_expires_at text,
  http_status integer,
  source_etag text,
  source_last_modified_at text,
  payload_hash text,
  parser_version text,
  current_fetch_artifact_id text,
  current_normalization_artifact_id text,
  verified_normalization_artifact_id text,
  published_normalization_artifact_id text,
  article_id text,
  duplicate_of_item_id text,
  exclusion_code text,
  error_code text,
  error_summary text,
  waived_by text,
  waived_at text,
  waiver_reason text,
  waiver_expires_at text,
  first_seen_at text not null,
  last_seen_at text not null,
  updated_at text not null,
  inventory_metadata text not null default '{}',
  primary key (id)
);
create index if not exists source_backfill_items_claim_idx on source_backfill_items (snapshot_id, status, next_attempt_at, first_seen_at);
create index if not exists source_backfill_items_claim_lease_idx on source_backfill_items (lease_expires_at, claimed_attempt_id);

create table if not exists source_backfill_runs (
  id text not null,
  snapshot_id text not null,
  command_run_id text,
  p1_attempt_id text,
  p1_fencing_token text,
  phase text not null check (phase in ('discover', 'fetch', 'normalize', 'verify', 'publish', 'reconcile')),
  pass_number integer not null,
  status text not null check (status in ('queued', 'running', 'deferred', 'succeeded', 'degraded', 'failed', 'aborted')),
  claimed_count integer not null default 0,
  succeeded_count integer not null default 0,
  retryable_failed_count integer not null default 0,
  terminal_failed_count integer not null default 0,
  cursor_in text,
  cursor_out text,
  page_manifest_hash text,
  heartbeat_at text,
  started_at text not null,
  completed_at text,
  last_error_code text,
  last_error_summary text,
  primary key (id)
);
create index if not exists source_backfill_runs_snapshot_phase_idx on source_backfill_runs (snapshot_id, phase, pass_number);

create table if not exists source_fetch_artifacts (
  id text not null,
  item_id text not null,
  source_policy_version text not null,
  authority_url text not null,
  http_status integer not null,
  response_headers_allowlist text not null default '{}',
  source_etag text,
  source_last_modified_at text,
  payload_hash text not null,
  payload_size text not null,
  replayability text not null,
  immutable_storage_ref text,
  bounded_replay_payload text,
  fetched_at text not null,
  fetch_contract_version text not null,
  created_at text not null,
  bounded_replay_storage_ref text,
  externalized_at text,
  externalization_contract_version text,
  primary key (id)
);
create index if not exists source_fetch_artifacts_item_created_idx on source_fetch_artifacts (item_id, created_at);

create table if not exists source_inventory_enumeration_artifacts (
  id text not null,
  snapshot_id text not null,
  source_key text not null,
  provider_key text not null,
  artifact_kind text not null check (artifact_kind in ('page', 'boundary_probe', 'crosscheck')),
  sequence_no integer not null,
  request_url text not null,
  response_hash text not null,
  record_manifest_hash text not null,
  record_count integer not null,
  newest_decision_date text,
  oldest_decision_date text,
  observed_last_page integer,
  safe_details text not null default '{}',
  observed_at text not null,
  primary key (id)
);

create table if not exists source_inventory_snapshot_supersessions (
  id text not null,
  snapshot_id text not null,
  source_key text not null,
  source_policy_version text not null,
  prior_parser_version text not null,
  replacement_parser_version text not null,
  prior_manifest_hash text not null,
  prior_enumeration_manifest_hash text not null,
  discovered_count integer not null,
  reason_code text not null,
  requested_by text not null,
  superseded_at text not null,
  primary key (id)
);

create table if not exists source_inventory_snapshots (
  id text not null,
  source_key text not null,
  scope_from text,
  scope_to text,
  document_type text not null,
  discovery_method text not null,
  parser_version text not null,
  source_policy_version text not null,
  coverage_assurance text not null check (coverage_assurance in ('authoritative_enumerated', 'authoritative_counted', 'authoritative_crosschecked', 'external_index_assisted', 'best_effort')),
  expected_count integer,
  expected_count_basis text,
  coverage_evidence text not null default '{}',
  discovered_count integer not null default 0,
  manifest_hash text,
  status text not null default 'open' check (status in ('open', 'closed', 'superseded', 'failed')),
  exclusions text not null default '[]',
  opened_at text not null,
  closed_at text,
  created_by text not null,
  enumeration_manifest_hash text,
  primary key (id)
);
create index if not exists source_inventory_snapshots_scope_idx on source_inventory_snapshots (source_key, document_type, scope_from, scope_to, opened_at);

create table if not exists source_normalization_artifacts (
  id text not null,
  item_id text not null,
  fetch_artifact_id text not null,
  parser_version text not null,
  normalization_contract_version text not null,
  normalized_output text,
  normalized_output_hash text not null,
  validation_status text not null check (validation_status in ('valid', 'invalid')),
  validation_errors text not null default '[]',
  created_at text not null,
  normalized_output_storage_ref text,
  normalized_output_size text,
  externalized_at text,
  externalization_contract_version text,
  primary key (id)
);
create index if not exists source_normalization_artifacts_item_created_idx on source_normalization_artifacts (item_id, created_at);

create table if not exists source_request_governor_states (
  source_key text not null,
  last_request_started_at text,
  next_request_not_before text not null,
  updated_at text not null,
  primary key (source_key)
);

create table if not exists source_request_permits (
  id text not null,
  source_key text not null,
  source_policy_version text not null,
  snapshot_id text not null,
  phase text not null check (phase in ('discover', 'fetch')),
  p1_attempt_id text not null,
  p1_fencing_token text not null,
  request_origin text not null,
  acquired_at text not null,
  lease_expires_at text not null,
  released_at text,
  primary key (id)
);
create index if not exists source_request_permits_active_idx on source_request_permits (source_key, lease_expires_at);
create index if not exists source_request_permits_attempt_idx on source_request_permits (p1_attempt_id, acquired_at);

create table if not exists source_url_candidates (
  id text not null,
  source_key text not null,
  url text not null,
  candidate_type text not null,
  discovered_by text not null,
  status text not null default 'pending' check (status in ('pending', 'retrying', 'fetched', 'failed', 'ignored')),
  last_attempt_at text,
  attempt_count integer not null default 0,
  last_error_code text,
  last_error_message text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists source_url_candidates_source_key_url_key on source_url_candidates (source_key, url);

create table if not exists us_conan_candidate_authority_artifacts_v1 (
  id text not null,
  candidate_id text not null,
  resolver_version text not null,
  resolution_hash text not null,
  status text not null check (status in ('verified', 'not_found', 'mismatch', 'blocked')),
  citation text not null,
  official_case_name text,
  details_url text not null,
  pdf_url text,
  payload_hash text,
  blocking text not null default '[]',
  observed_at text not null,
  created_at text not null,
  primary key (id)
);
create index if not exists us_conan_candidate_authority_latest_idx on us_conan_candidate_authority_artifacts_v1 (candidate_id, observed_at, created_at);

create table if not exists us_conan_candidate_catalog_events_v1 (
  id text not null,
  candidate_id text not null,
  candidate_snapshot_id text not null,
  candidate_manifest_hash text not null,
  review_id text not null,
  review_revision integer not null,
  authority_artifact_id text not null,
  publication_source_key text not null default 'us-scotus',
  source_policy_version text not null,
  article_id text not null,
  source_anchor_version_id text not null,
  version_revision text not null,
  catalog_publication_id text not null,
  publication_revision text not null,
  idempotency_key text not null,
  actor_id text not null,
  created_at text not null,
  primary key (id)
);

create table if not exists us_conan_candidate_essay_evidence_v1 (
  id text not null,
  candidate_id text not null,
  essay_id text not null,
  essay_title text not null,
  essay_url text not null,
  created_at text not null,
  primary key (id)
);

create table if not exists us_conan_candidate_reviews_v1 (
  id text not null,
  candidate_id text not null,
  revision integer not null,
  status text not null check (status in ('verified', 'uncertain', 'rejected')),
  official_scotus_identity_verified integer not null,
  constitutional_essay_context_verified integer not null,
  official_authority_verified integer not null,
  constitutional_holding_verified integer not null,
  official_authority_url text,
  safe_evidence text not null default '{}',
  reviewed_by text not null,
  review_reason text not null,
  reviewed_at text not null,
  authority_artifact_id text,
  essay_evidence_ids text not null default '[]',
  holding_evidence text not null default '[]',
  primary key (id)
);
create index if not exists us_conan_candidate_reviews_latest_idx on us_conan_candidate_reviews_v1 (candidate_id, revision);

create table if not exists us_conan_candidate_snapshots_v1 (
  id text not null,
  source_key text not null default 'us-constitution-annotated',
  source_url text not null,
  source_policy_version text not null,
  payload_hash text not null,
  parser_version text not null,
  capture_mode text not null check (capture_mode in ('official_live', 'reviewed_fixture')),
  citation_coverage_assurance text not null,
  status text not null default 'open',
  candidate_count integer not null default 0,
  manifest_hash text,
  observed_at text not null,
  opened_at text not null,
  closed_at text,
  created_by text not null,
  primary key (id)
);

create table if not exists us_conan_case_candidates_v1 (
  id text not null,
  snapshot_id text not null,
  stable_candidate_key text not null,
  case_name text not null,
  citation text not null,
  normalized_citation text not null,
  court_classification text not null check (court_classification in ('scotus_candidate', 'lower_federal', 'state_or_other', 'unknown')),
  candidate_basis text not null default 'constitution_annotated_table_citation',
  priority integer not null default 0,
  priority_reasons text not null default '[]',
  created_at text not null,
  primary key (id)
);
create index if not exists us_conan_case_candidates_classification_idx on us_conan_case_candidates_v1 (snapshot_id, court_classification, priority, normalized_citation);
