-- WorldCons D1 schema: worldcons_ingest
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists ingestion_runs (
  id text not null,
  source_key text not null,
  started_at text not null,
  finished_at text,
  status text not null,
  discovered_count integer not null default 0,
  fetched_count integer not null default 0,
  summarized_count integer not null default 0,
  failed_count integer not null default 0,
  error_message text,
  metadata text,
  primary key (id)
);

create table if not exists source_url_candidates (
  id text not null,
  source_key text not null,
  url text not null,
  candidate_type text not null,
  discovered_by text not null,
  status text not null default 'pending' check (status in ('pending', 'retrying', 'fetched', 'failed', 'ignored')),
  last_attempt_at text,
  attempt_count integer not null default 0,
  last_error_code text,
  last_error_message text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists source_url_candidates_source_key_url_key on source_url_candidates (source_key, url);
