import type { D1TableDefinition } from "../types";
import { buildTable, uniqueIndex, type TableSpec } from "./shared";

/** Postgres `articles_status_check` values. */
export const ARTICLE_STATUS_VALUES = [
  "discovered",
  "metadata_only",
  "robots_disallowed",
  "blocked",
  "timeout",
  "fetched",
  "cleaned",
  "summarizing",
  "summarized",
  "failed_fetch",
  "failed_summary",
  "needs_review",
] as const;

/** Postgres `articles_content_type_check` values. */
export const ARTICLE_CONTENT_TYPE_VALUES = ["news", "press_release", "decision", "opinion", "order", "other"] as const;

const sources: TableSpec = {
  name: "sources",
  database: "worldcons_core",
  primaryKey: ["id"],
  indexes: [uniqueIndex("sources_source_key_key", ["source_key"])],
  columns: [
    { name: "id", type: "uuid", nn: true, note: "application-generated UUID" },
    { name: "source_key", type: "text", nn: true },
    { name: "name", type: "text", nn: true },
    { name: "jurisdiction", type: "text", nn: true },
    { name: "base_url", type: "text", nn: true },
    { name: "language", type: "text", nn: true },
    { name: "is_active", type: "boolean", nn: true, def: "1" },
    { name: "created_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "updated_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
  ],
};
const articles: TableSpec = {
  name: "articles",
  database: "worldcons_core",
  primaryKey: ["id"],
  indexes: [
    uniqueIndex("articles_slug_key", ["slug"]),
    uniqueIndex("articles_canonical_url_key", ["canonical_url"]),
    uniqueIndex("articles_id_source_key_v4_key", ["id", "source_key"]),
  ],
  columns: [
    { name: "id", type: "uuid", nn: true, note: "application-generated UUID" },
    { name: "source_id", type: "uuid" },
    { name: "source_key", type: "text", nn: true },
    { name: "jurisdiction", type: "text", nn: true },
    { name: "institution_name", type: "text", nn: true },
    { name: "content_type", type: "text", nn: true, enum: ARTICLE_CONTENT_TYPE_VALUES },
    { name: "original_url", type: "text", nn: true },
    { name: "canonical_url", type: "text", nn: true },
    { name: "original_language", type: "text", nn: true },
    { name: "original_title", type: "text" },
    { name: "korean_title", type: "text" },
    { name: "original_published_at", type: "timestamptz" },
    { name: "discovered_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "fetched_at", type: "timestamptz" },
    { name: "summarized_at", type: "timestamptz" },
    { name: "status", type: "text", nn: true, def: "'discovered'", enum: ARTICLE_STATUS_VALUES },
    { name: "slug", type: "text", nn: true },
    { name: "raw_text", type: "text", note: "inline cleared to R2 only after verified externalization (plan 7.3)" },    { name: "cleaned_text", type: "text", note: "inline cleared to R2 only after verified externalization (plan 7.3)" },
    { name: "summary_json", type: "jsonb" },
    { name: "search_vector", type: "tsvector", note: "relocated to the worldcons_search FTS5 projection" },
    { name: "embedding", type: "vector(1536)", note: "relocated to the Vectorize index" },
    { name: "content_hash", type: "text" },
    { name: "source_metadata", type: "jsonb" },
    { name: "error_metadata", type: "jsonb" },
    { name: "created_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "updated_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "error_class", type: "text" },
    { name: "error_context", type: "jsonb" },
    { name: "review_state", type: "text" },
    { name: "lifecycle_collection_state", type: "text" },
    { name: "lifecycle_processing_state", type: "text" },
    { name: "lifecycle_review_state", type: "text" },
    { name: "lifecycle_attention_state", type: "text" },
    { name: "lifecycle_attention_code", type: "text" },
    { name: "lifecycle_attention_retryable", type: "boolean" },
    { name: "lifecycle_attention_severity", type: "text" },
    { name: "lifecycle_attention_source", type: "text" },    { name: "lifecycle_attention_raised_at", type: "timestamptz" },
    { name: "lifecycle_attention_cleared_at", type: "timestamptz" },
    { name: "lifecycle_revision", type: "bigint", nn: true, def: "0", note: "decimal TEXT (plan 6.1 bigint rule)" },
    { name: "lifecycle_changed_at", type: "timestamptz" },
    { name: "lifecycle_collection_changed_at", type: "timestamptz" },
    { name: "lifecycle_processing_changed_at", type: "timestamptz" },
    { name: "lifecycle_review_changed_at", type: "timestamptz" },
    { name: "lifecycle_attention_changed_at", type: "timestamptz" },
    { name: "case_key", type: "text" },
    { name: "embedding_provider", type: "text" },
    { name: "embedding_model", type: "text" },
    { name: "embedding_dimensions", type: "integer" },
    { name: "embedding_input_hash", type: "text" },
    { name: "embedding_generated_at", type: "timestamptz" },
    { name: "catalog_ai_stale_v4", type: "boolean", nn: true, def: "0" },
    { name: "raw_text_storage_ref", type: "text" },
    { name: "raw_text_blob_hash", type: "text" },
    { name: "raw_text_blob_size", type: "bigint", note: "decimal TEXT (plan 6.1 bigint rule)" },
    { name: "raw_text_externalized_at", type: "timestamptz" },
    { name: "raw_text_blob_contract_version", type: "text" },
  ],
};
const tags: TableSpec = {
  name: "tags",
  database: "worldcons_core",
  primaryKey: ["id"],
  indexes: [uniqueIndex("tags_slug_key", ["slug"])],
  columns: [
    { name: "id", type: "uuid", nn: true, note: "application-generated UUID" },
    { name: "slug", type: "text", nn: true },
    { name: "name", type: "text", nn: true },
    { name: "normalized_name", type: "text", nn: true },
    { name: "type", type: "text", nn: true },
    { name: "description", type: "text" },
    { name: "article_count", type: "integer", nn: true, def: "0" },
    { name: "latest_article_at", type: "timestamptz" },
    { name: "created_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "updated_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
  ],
};

const articleTags: TableSpec = {
  name: "article_tags",
  database: "worldcons_core",
  primaryKey: ["article_id", "tag_id"],
  columns: [
    { name: "article_id", type: "uuid", nn: true, note: "logical FK to articles.id (no cross-DB/cross-table FK in D1)" },
    { name: "tag_id", type: "uuid", nn: true, note: "logical FK to tags.id" },
    { name: "confidence", type: "numeric", note: "REAL (plan 6.1) - tag confidence is a small float" },
    { name: "created_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
  ],
};
const glossaryTerms: TableSpec = {
  name: "glossary_terms",
  database: "worldcons_core",
  primaryKey: ["id"],
  indexes: [uniqueIndex("glossary_terms_slug_key", ["slug"])],
  columns: [
    { name: "id", type: "uuid", nn: true, note: "application-generated UUID" },
    { name: "slug", type: "text", nn: true },
    { name: "term", type: "text", nn: true },
    { name: "korean_term", type: "text" },
    { name: "definition", type: "text" },
    { name: "jurisdiction", type: "text" },
    { name: "related_tags", type: "text[]", note: "array -> canonical JSON TEXT (plan 6.1)" },
    { name: "created_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
    { name: "updated_at", type: "timestamptz", nn: true, note: "application-generated UTC ISO-8601" },
  ],
};

export const coreTables: D1TableDefinition[] = [sources, articles, tags, articleTags, glossaryTerms].map(buildTable);