import type { D1ColumnDefinition, D1Database, D1Schema, D1StorageKind, D1TableDefinition } from "./types";

export interface D1DdlEmitOptions {
  /** Emit only the historical Postgres-derived baseline, excluding D1-native additive columns/indexes. */
  baseline?: boolean;
}

/**
 * Deterministic local D1 DDL emitter.
 *
 * The emitted SQL is plain SQLite/D1 DDL for local application only (for
 * example `wrangler d1 execute <db> --local --file=d1/<db>/0001_init.sql` or an
 * in-memory `node:sqlite` run). M5.1 never creates a remote database.
 */
const SQL_TYPES: Record<D1StorageKind, string> = {
  text: "text",
  integer: "integer",
  real: "real",
  blob: "blob",
};

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function emitColumn(column: D1ColumnDefinition): string {
  const parts = [column.name, SQL_TYPES[column.kind]];
  if (column.notNull) parts.push("not null");
  if (column.defaultSql !== null) parts.push(`default ${column.defaultSql}`);
  if (column.enumValues && column.enumValues.length > 0) {
    parts.push(`check (${column.name} in (${column.enumValues.map(sqlString).join(", ")}))`);
  }
  return parts.join(" ");
}
export function emitTableDdl(table: D1TableDefinition, options: D1DdlEmitOptions = {}): string {
  if (table.virtual) {
    return `create virtual table if not exists ${table.name} using ${table.virtual.module}(${table.virtual.columns.join(", ")});`;
  }
  const columns = options.baseline ? table.columns.filter((column) => column.origin !== "native") : table.columns;
  const columnNames = new Set(columns.map((column) => column.name));
  const lines = columns.map((column) => `  ${emitColumn(column)}`);
  if (table.primaryKey.length > 0) lines.push(`  primary key (${table.primaryKey.join(", ")})`);
  const createTable = `create table if not exists ${table.name} (\n${lines.join(",\n")}\n);`;
  const indexes = table.indexes
    .filter((index) => !options.baseline || index.columns.every((column) => columnNames.has(column)))
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((index) => `create ${index.unique ? "unique " : ""}index if not exists ${index.name} on ${table.name} (${index.columns.join(", ")});`);
  return [createTable, ...indexes].join("\n");
}

export function emitDatabaseDdl(database: D1Database, schema: D1Schema, options: D1DdlEmitOptions = {}): string {
  const tables = schema.tables
    .filter((table) => table.database === database)
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name));
  const body = tables.map((table) => emitTableDdl(table, options)).join("\n\n");
  const header = [
    `-- WorldCons D1 schema: ${database}`,
    "-- LOCAL ONLY. Generated by \"pnpm d1:schema --emit\".",
    "-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).",
  ].join("\n");
  return `${header}\n\n${body}\n`;
}

export function emitAllDatabaseDdl(schema: D1Schema, options: D1DdlEmitOptions = {}): Record<D1Database, string> {
  const result = {} as Record<D1Database, string>;
  for (const database of schema.databases) result[database] = emitDatabaseDdl(database, schema, options);
  return result;
}
