-- WorldCons D1 schema: worldcons_core
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists article_tags (
  article_id text not null,
  tag_id text not null,
  confidence real,
  created_at text not null,
  primary key (article_id, tag_id)
);

create table if not exists articles (
  id text not null,
  source_id text,
  source_key text not null,
  jurisdiction text not null,
  institution_name text not null,
  content_type text not null check (content_type in ('news', 'press_release', 'decision', 'opinion', 'order', 'other')),
  original_url text not null,
  canonical_url text not null,
  original_language text not null,
  original_title text,
  korean_title text,
  original_published_at text,
  discovered_at text not null,
  fetched_at text,
  summarized_at text,
  status text not null default 'discovered' check (status in ('discovered', 'metadata_only', 'robots_disallowed', 'blocked', 'timeout', 'fetched', 'cleaned', 'summarizing', 'summarized', 'failed_fetch', 'failed_summary', 'needs_review')),
  slug text not null,
  raw_text text,
  cleaned_text text,
  summary_json text,
  content_hash text,
  source_metadata text,
  error_metadata text,
  created_at text not null,
  updated_at text not null,
  error_class text,
  error_context text,
  review_state text,
  lifecycle_collection_state text,
  lifecycle_processing_state text,
  lifecycle_review_state text,
  lifecycle_attention_state text,
  lifecycle_attention_code text,
  lifecycle_attention_retryable integer,
  lifecycle_attention_severity text,
  lifecycle_attention_source text,
  lifecycle_attention_raised_at text,
  lifecycle_attention_cleared_at text,
  lifecycle_revision text not null default 0,
  lifecycle_changed_at text,
  lifecycle_collection_changed_at text,
  lifecycle_processing_changed_at text,
  lifecycle_review_changed_at text,
  lifecycle_attention_changed_at text,
  case_key text,
  embedding_provider text,
  embedding_model text,
  embedding_dimensions integer,
  embedding_input_hash text,
  embedding_generated_at text,
  catalog_ai_stale_v4 integer not null default 0,
  raw_text_storage_ref text,
  raw_text_blob_hash text,
  raw_text_blob_size text,
  raw_text_externalized_at text,
  raw_text_blob_contract_version text,
  primary key (id)
);
create unique index if not exists articles_canonical_url_key on articles (canonical_url);
create unique index if not exists articles_id_source_key_v4_key on articles (id, source_key);
create unique index if not exists articles_slug_key on articles (slug);

create table if not exists glossary_terms (
  id text not null,
  slug text not null,
  term text not null,
  korean_term text,
  definition text,
  jurisdiction text,
  related_tags text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists glossary_terms_slug_key on glossary_terms (slug);

create table if not exists sources (
  id text not null,
  source_key text not null,
  name text not null,
  jurisdiction text not null,
  base_url text not null,
  language text not null,
  is_active integer not null default 1,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists sources_source_key_key on sources (source_key);

create table if not exists tags (
  id text not null,
  slug text not null,
  name text not null,
  normalized_name text not null,
  type text not null,
  description text,
  article_count integer not null default 0,
  latest_article_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists tags_slug_key on tags (slug);
