-- WorldCons D1 schema: worldcons_core
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists article_audit_ledger_p3 (
  id text not null,
  article_id text not null,
  ledger_revision text not null,
  event_type text not null,
  article_version_id text,
  publication_id text,
  publication_revision text,
  actor_type text not null check (actor_type in ('human', 'llm', 'import', 'compatibility', 'backfill', 'system')),
  actor_id text,
  reason text not null,
  request_id text,
  correlation_id text,
  safe_metadata text not null default '{}',
  previous_entry_hash text,
  entry_hash text not null,
  occurred_at text not null,
  primary key (id)
);
create unique index if not exists article_audit_ledger_p3_article_revision_key on article_audit_ledger_p3 (article_id, ledger_revision);
create unique index if not exists article_audit_ledger_p3_entry_hash_key on article_audit_ledger_p3 (entry_hash);
create index if not exists article_audit_ledger_p3_event_occurred_idx on article_audit_ledger_p3 (event_type, occurred_at);

create table if not exists article_cache_outbox_p3 (
  id text not null,
  event_key text not null,
  event_type text not null,
  article_id text not null,
  publication_id text not null,
  publication_revision text not null,
  version_id text not null,
  publication_state text not null check (publication_state in ('draft', 'in_review', 'published', 'withdrawn')),
  article_slug text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'delivered', 'dead_letter')),
  attempt_count integer not null default 0,
  max_attempts integer not null default 12,
  available_at text not null,
  lease_owner text,
  lease_token text,
  lease_expires_at text,
  last_error_code text,
  delivered_at text,
  dead_lettered_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create index if not exists article_cache_outbox_p3_claim_idx on article_cache_outbox_p3 (available_at, created_at, id);
create index if not exists article_cache_outbox_p3_dead_letter_idx on article_cache_outbox_p3 (dead_lettered_at, id);
create unique index if not exists article_cache_outbox_p3_event_key_key on article_cache_outbox_p3 (event_key);
create index if not exists article_cache_outbox_p3_lease_idx on article_cache_outbox_p3 (lease_expires_at, id);
create unique index if not exists article_cache_outbox_p3_publication_revision_key on article_cache_outbox_p3 (publication_id, publication_revision);

create table if not exists article_content_versions_p3 (
  id text not null,
  article_id text not null,
  revision text not null,
  parent_version_id text,
  content_hash text not null,
  provenance_actor_type text not null check (provenance_actor_type in ('human', 'llm', 'import')),
  provenance_actor_id text,
  model_ref text,
  prompt_ref text,
  slug text not null,
  source_key text not null,
  jurisdiction text not null,
  institution_name text not null,
  content_type text not null check (content_type in ('news', 'press_release', 'decision', 'opinion', 'order', 'other')),
  original_url text not null,
  canonical_url text not null,
  original_language text not null,
  original_title text,
  korean_title text,
  original_published_at text,
  discovered_at text,
  fetched_at text,
  summarized_at text,
  raw_text text,
  cleaned_text text,
  summary_json text,
  source_metadata text,
  error_metadata text,
  created_at text not null,
  case_key text,
  version_document_schema text not null default 'p3.article.v1' check (version_document_schema in ('p3.article.v1', 'v4.article-case.v1')),
  version_role text,
  case_metadata_snapshot text,
  case_identifiers_snapshot text,
  authority_evidence_hash text,
  source_snapshot_id text,
  source_snapshot_hash text,
  source_content_hash text,
  source_anchor_version_id text,
  enrichment_source_content_hash text,
  raw_text_storage_ref text,
  raw_text_blob_hash text,
  raw_text_blob_size text,
  raw_text_externalized_at text,
  raw_text_blob_contract_version text,
  primary key (id)
);
create index if not exists article_content_versions_p3_article_created_idx on article_content_versions_p3 (article_id, created_at);
create unique index if not exists article_content_versions_p3_article_hash_key on article_content_versions_p3 (article_id, content_hash);
create unique index if not exists article_content_versions_p3_article_revision_key on article_content_versions_p3 (article_id, revision);
create index if not exists article_content_versions_p3_jurisdiction_order_idx on article_content_versions_p3 (jurisdiction, original_published_at, article_id);
create index if not exists article_content_versions_p3_public_order_idx on article_content_versions_p3 (original_published_at, article_id);
create index if not exists article_content_versions_p3_source_case_key_idx on article_content_versions_p3 (source_key, case_key);
create index if not exists article_content_versions_p3_source_order_idx on article_content_versions_p3 (source_key, original_published_at, article_id);

create table if not exists article_embedding_artifacts (
  article_version_id text not null,
  article_id text not null,
  content_hash text not null,
  provider text not null,
  model text not null,
  dimensions integer not null,
  input_hash text not null,
  generated_at text not null,
  updated_at text not null,
  primary key (article_version_id)
);
create index if not exists article_embedding_artifacts_article_idx on article_embedding_artifacts (article_id, generated_at);
create unique index if not exists article_embedding_artifacts_article_version_key on article_embedding_artifacts (article_id, article_version_id);

create table if not exists article_lifecycle_anomalies_p2 (
  article_id text not null,
  legacy_status text not null,
  anomaly_code text not null,
  first_seen_at text not null,
  last_seen_at text not null,
  occurrence_count integer not null default 1,
  resolved_at text,
  primary key (article_id)
);

create table if not exists article_lifecycle_events_p2 (
  id text not null,
  article_id text not null,
  idempotency_key text not null,
  from_revision text not null,
  to_revision text not null,
  actor_type text not null check (actor_type in ('ingestion', 'summary_worker', 'admin', 'candidate', 'backfill', 'system', 'compatibility')),
  actor_id text,
  transition_source text not null,
  reason_code text not null,
  applied integer not null,
  collection_state text,
  processing_state text,
  review_state text,
  attention_state text,
  attention_code text,
  attention_retryable integer,
  attention_severity text,
  attention_source text,
  occurred_at text not null,
  primary key (id)
);
create unique index if not exists article_lifecycle_events_p2_article_key_key on article_lifecycle_events_p2 (article_id, idempotency_key);

create table if not exists article_publication_history_p3 (
  id text not null,
  publication_id text not null,
  article_id text not null,
  publication_revision text not null,
  from_state text,
  to_state text not null,
  from_version_id text,
  to_version_id text not null,
  idempotency_key text not null,
  actor_type text not null check (actor_type in ('human', 'compatibility', 'backfill', 'system')),
  actor_id text,
  reason text not null,
  request_id text,
  correlation_id text,
  occurred_at text not null,
  primary key (id)
);
create unique index if not exists article_publication_history_p3_article_key on article_publication_history_p3 (article_id, idempotency_key);
create index if not exists article_publication_history_p3_article_occurred_idx on article_publication_history_p3 (article_id, occurred_at);
create unique index if not exists article_publication_history_p3_revision_key on article_publication_history_p3 (publication_id, publication_revision);

create table if not exists article_publication_quarantine_p3 (
  id text not null,
  article_id text not null,
  anomaly_code text not null,
  legacy_public integer not null,
  detected_at text not null,
  primary key (id)
);
create unique index if not exists article_publication_quarantine_p3_article_code_key on article_publication_quarantine_p3 (article_id, anomaly_code);

create table if not exists article_publication_quarantine_resolutions_p3 (
  article_id text not null,
  anomaly_code text not null,
  resolution_code text not null,
  resolved_at text not null,
  primary key (article_id, anomaly_code)
);

create table if not exists article_publication_requests_p3 (
  id text not null,
  article_id text not null,
  idempotency_key text not null,
  publication_id text not null,
  publication_revision text not null,
  version_id text not null,
  version_revision text not null,
  state text not null check (state in ('draft', 'in_review', 'published', 'withdrawn')),
  version_created integer not null,
  publication_applied integer not null,
  created_at text not null,
  primary key (id)
);
create unique index if not exists article_publication_requests_p3_article_key on article_publication_requests_p3 (article_id, idempotency_key);

create table if not exists article_publications_p3 (
  id text not null,
  article_id text not null,
  state text not null check (state in ('draft', 'in_review', 'published', 'withdrawn')),
  version_id text not null,
  revision text not null,
  decided_by_type text not null check (decided_by_type in ('human', 'compatibility', 'backfill', 'system')),
  decided_by_id text,
  reason text not null,
  published_at text,
  withdrawn_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists article_publications_p3_article_id_key on article_publications_p3 (article_id);
create index if not exists article_publications_p3_state_version_idx on article_publications_p3 (state, version_id, article_id);

create table if not exists article_revision_heads_v4 (
  article_id text not null,
  current_version_id text not null,
  current_revision text not null,
  updated_at text not null,
  primary key (article_id)
);

create table if not exists article_tags (
  article_id text not null,
  tag_id text not null,
  confidence real,
  created_at text not null,
  primary key (article_id, tag_id)
);

create table if not exists article_version_heads_p3 (
  article_id text not null,
  current_version_id text not null,
  current_revision text not null,
  updated_at text not null,
  primary key (article_id)
);

create table if not exists article_view_counts (
  article_slug text not null,
  article_id text,
  view_count text not null default 0,
  updated_at text not null,
  primary key (article_slug)
);
create index if not exists article_view_counts_view_count_idx on article_view_counts (view_count);

create table if not exists articles (
  id text not null,
  source_id text,
  source_key text not null,
  jurisdiction text not null,
  institution_name text not null,
  content_type text not null check (content_type in ('news', 'press_release', 'decision', 'opinion', 'order', 'other')),
  original_url text not null,
  canonical_url text not null,
  original_language text not null,
  original_title text,
  korean_title text,
  original_published_at text,
  discovered_at text not null,
  fetched_at text,
  summarized_at text,
  status text not null default 'discovered' check (status in ('discovered', 'metadata_only', 'robots_disallowed', 'blocked', 'timeout', 'fetched', 'cleaned', 'summarizing', 'summarized', 'failed_fetch', 'failed_summary', 'needs_review')),
  slug text not null,
  raw_text text,
  cleaned_text text,
  summary_json text,
  content_hash text,
  source_metadata text,
  error_metadata text,
  created_at text not null,
  updated_at text not null,
  error_class text,
  error_context text,
  review_state text,
  lifecycle_collection_state text,
  lifecycle_processing_state text,
  lifecycle_review_state text,
  lifecycle_attention_state text,
  lifecycle_attention_code text,
  lifecycle_attention_retryable integer,
  lifecycle_attention_severity text,
  lifecycle_attention_source text,
  lifecycle_attention_raised_at text,
  lifecycle_attention_cleared_at text,
  lifecycle_revision text not null default 0,
  lifecycle_changed_at text,
  lifecycle_collection_changed_at text,
  lifecycle_processing_changed_at text,
  lifecycle_review_changed_at text,
  lifecycle_attention_changed_at text,
  case_key text,
  embedding_provider text,
  embedding_model text,
  embedding_dimensions integer,
  embedding_input_hash text,
  embedding_generated_at text,
  catalog_ai_stale_v4 integer not null default 0,
  raw_text_storage_ref text,
  raw_text_blob_hash text,
  raw_text_blob_size text,
  raw_text_externalized_at text,
  raw_text_blob_contract_version text,
  primary key (id)
);
create unique index if not exists articles_canonical_url_key on articles (canonical_url);
create unique index if not exists articles_id_source_key_v4_key on articles (id, source_key);
create unique index if not exists articles_slug_key on articles (slug);

create table if not exists case_catalog_cache_outbox_v1 (
  id text not null,
  event_key text not null,
  article_id text not null,
  publication_id text not null,
  publication_revision text not null,
  source_anchor_version_id text not null,
  article_slug text not null,
  created_at text not null,
  primary key (id)
);
create unique index if not exists case_catalog_cache_outbox_v1_event_key_key on case_catalog_cache_outbox_v1 (event_key);
create unique index if not exists case_catalog_cache_outbox_v1_revision_key on case_catalog_cache_outbox_v1 (publication_id, publication_revision);

create table if not exists case_catalog_publication_events_v1 (
  id text not null,
  publication_id text not null,
  article_id text not null,
  publication_revision text not null,
  from_state text,
  to_state text not null,
  previous_source_anchor_version_id text,
  next_source_anchor_version_id text not null,
  idempotency_key text not null,
  actor_type text not null,
  actor_id text,
  reason text not null,
  occurred_at text not null,
  primary key (id)
);
create unique index if not exists case_catalog_publication_events_v1_article_key on case_catalog_publication_events_v1 (article_id, idempotency_key);
create unique index if not exists case_catalog_publication_events_v1_revision_key on case_catalog_publication_events_v1 (publication_id, publication_revision);

create table if not exists case_catalog_publications_v1 (
  id text not null,
  article_id text not null,
  state text not null check (state in ('published', 'withdrawn')),
  source_anchor_version_id text not null,
  revision text not null,
  source_policy_version text not null,
  decided_by_type text not null check (decided_by_type in ('human', 'backfill', 'system')),
  decided_by_id text,
  reason text not null,
  published_at text,
  withdrawn_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists case_catalog_publications_v1_article_id_key on case_catalog_publications_v1 (article_id);

create table if not exists case_identifiers_v1 (
  id text not null,
  article_id text not null,
  source_key text not null,
  identifier_type text not null check (identifier_type in ('source_record_id', 'ecli', 'docket', 'decision_number', 'reporter_citation', 'hj_id', 'case_key')),
  identifier_scope text not null check (identifier_scope in ('decision', 'proceeding', 'lookup')),
  raw_value text not null,
  normalized_value text not null,
  normalization_version integer not null default 1,
  is_primary integer not null default 0,
  provenance_url text,
  created_at text not null,
  primary key (id)
);
create index if not exists case_identifiers_v1_normalized_search_idx on case_identifiers_v1 (normalized_value, identifier_type, article_id);
create index if not exists case_identifiers_v1_proceeding_lookup_idx on case_identifiers_v1 (source_key, identifier_type, normalized_value);

create table if not exists case_metadata_v1 (
  article_id text not null,
  source_key text not null,
  authority_status text not null check (authority_status in ('candidate', 'verified', 'rejected', 'withdrawn')),
  authority_evidence text not null default '{}',
  constitutional_relevance_status text,
  enrichment_status text not null default 'source_only' check (enrichment_status in ('source_only', 'light', 'full')),
  enrichment_freshness text,
  freshness_basis text,
  text_access_policy text not null default 'metadata_only' check (text_access_policy in ('metadata_only', 'index_only', 'excerpt', 'full')),
  source_policy_version text not null,
  discovery_source text not null,
  authority_source text not null,
  source_last_modified_at text,
  source_etag text,
  source_snapshot_hash text,
  ai_priority integer not null default 0,
  created_at text not null,
  updated_at text not null,
  primary key (article_id)
);

create table if not exists glossary_candidates (
  id text not null,
  tag_slug text not null,
  tag_name text not null,
  tag_type text not null,
  article_count integer not null default 0,
  suggested_slug text not null,
  source_languages text not null default '[]',
  status text not null default 'pending' check (status in ('pending', 'approved', 'ignored')),
  generated_at text not null,
  reviewed_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create index if not exists glossary_candidates_status_count_idx on glossary_candidates (status, article_count);
create unique index if not exists glossary_candidates_tag_slug_key on glossary_candidates (tag_slug);

create table if not exists glossary_terms (
  id text not null,
  slug text not null,
  term text not null,
  korean_term text,
  definition text,
  jurisdiction text,
  related_tags text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists glossary_terms_slug_key on glossary_terms (slug);

create table if not exists legacy_version_freshness_classifications_v4 (
  version_id text not null,
  article_id text not null,
  freshness text not null check (freshness in ('current', 'stale')),
  freshness_basis text not null check (freshness_basis in ('source_hash_match', 'legacy_same_version', 'source_hash_mismatch', 'unknown_fail_closed')),
  source_anchor_version_id text,
  source_content_hash text,
  evidence text not null default '{}',
  classified_at text not null,
  classified_by text not null,
  primary key (version_id)
);

create table if not exists legal_concept_alias_sets_v1 (
  id text not null,
  set_version text not null,
  status text not null default 'draft' check (status in ('draft', 'reviewed')),
  provenance text not null,
  content_hash text,
  reviewed_by text,
  reviewed_at text,
  supersedes_alias_set_id text,
  created_at text not null,
  primary key (id)
);
create index if not exists legal_concept_alias_sets_v1_reviewed_idx on legal_concept_alias_sets_v1 (reviewed_at, id);
create unique index if not exists legal_concept_alias_sets_v1_set_version_key on legal_concept_alias_sets_v1 (set_version);

create table if not exists legal_concept_aliases_v1 (
  id text not null,
  alias_set_id text not null,
  concept_id text not null,
  language text not null check (language in ('ko', 'en', 'de', 'fr', 'es')),
  raw_alias text not null,
  normalized_alias text not null,
  alias_type text not null check (alias_type in ('preferred', 'synonym', 'translated', 'acronym', 'historical')),
  provenance text not null,
  review_status text not null default 'pending' check (review_status in ('pending', 'approved', 'rejected')),
  created_at text not null,
  primary key (id)
);
create unique index if not exists legal_concept_aliases_v1_alias_identity_key on legal_concept_aliases_v1 (alias_set_id, language, normalized_alias, concept_id);
create index if not exists legal_concept_aliases_v1_concept_idx on legal_concept_aliases_v1 (alias_set_id, concept_id, language, alias_type);
create index if not exists legal_concept_aliases_v1_lookup_idx on legal_concept_aliases_v1 (alias_set_id, normalized_alias, concept_id);

create table if not exists legal_concepts_v1 (
  id text not null,
  alias_set_id text not null,
  stable_key text not null,
  label_ko text not null,
  definition text,
  status text not null default 'active' check (status in ('active', 'retired')),
  version integer not null default 1,
  created_at text not null,
  primary key (id)
);
create unique index if not exists legal_concepts_v1_alias_set_stable_key_key on legal_concepts_v1 (alias_set_id, stable_key);
create unique index if not exists legal_concepts_v1_id_alias_set_id_key on legal_concepts_v1 (id, alias_set_id);

create table if not exists source_corpus_policies (
  source_key text not null,
  policy_version text not null,
  scope_definition text not null,
  official_scope_url text not null,
  discovery_methods text not null,
  authority_hosts text not null,
  redirect_hosts text not null default '[]',
  robots_url text not null,
  robots_observed_at text not null,
  robots_rules_hash text not null,
  terms_url text,
  terms_observed_at text,
  license_basis text not null,
  default_text_access_policy text not null check (default_text_access_policy in ('metadata_only', 'index_only', 'excerpt', 'full')),
  allow_raw_snapshot integer not null default 0,
  normalize_replay_policy text not null check (normalize_replay_policy in ('full_snapshot', 'bounded_evidence', 'non_replayable')),
  bounded_replay_fields text not null default '[]',
  retention_days integer,
  min_request_delay_ms integer not null,
  max_concurrency integer not null,
  external_index_hosts text not null default '[]',
  external_index_usage text,
  reviewed_by text not null,
  reviewed_at text not null,
  review_due_at text not null,
  supersedes_policy_version text,
  created_at text not null,
  primary key (source_key, policy_version)
);

create table if not exists sources (
  id text not null,
  source_key text not null,
  name text not null,
  jurisdiction text not null,
  base_url text not null,
  language text not null,
  is_active integer not null default 1,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists sources_source_key_key on sources (source_key);

create table if not exists tags (
  id text not null,
  slug text not null,
  name text not null,
  normalized_name text not null,
  type text not null,
  description text,
  article_count integer not null default 0,
  latest_article_at text,
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists tags_slug_key on tags (slug);
