import type { GlossaryTerm } from "@/lib/db/types";

export const glossaryTermsSeed: GlossaryTerm[] = [
  {
    slug: "admissibility",
    term: "Admissibility / Zulassigkeit / Recevabilite",
    koreanTerm: "적법요건",
    definition: "헌법재판기관이 본안 판단에 들어가기 전에 청구권자, 기간, 대상, 보충성, 권리보호이익 같은 절차 요건을 충족했는지 보는 단계다.",
    jurisdiction: null,
    relatedTags: ["적법요건", "각하", "불수리"],
  },
  {
    slug: "annulment",
    term: "Annulment / Annulation",
    koreanTerm: "취소",
    definition: "선거, 행정행위, 법률 조항 등의 효력을 헌법 또는 법률 기준에 맞지 않는다는 이유로 제거하는 결론이다.",
    jurisdiction: null,
    relatedTags: ["취소", "무효", "선거무효"],
  },
  {
    slug: "as-applied-challenge",
    term: "As-applied challenge",
    koreanTerm: "적용상 위헌 주장",
    definition: "법률 자체가 모든 경우에 위헌이라는 주장이 아니라, 특정 사실관계나 당사자에게 적용되는 방식이 헌법에 어긋난다는 주장이다.",
    jurisdiction: "United States",
    relatedTags: ["As-applied challenge", "위헌심사"],
  },
  {
    slug: "bverfgg",
    term: "Bundesverfassungsgerichtsgesetz",
    koreanTerm: "연방헌법재판소법",
    definition: "독일 연방헌법재판소의 관할, 절차, 재판부 구성, 결정 방식 등을 정하는 법률이다.",
    jurisdiction: "Germany",
    relatedTags: ["BVerfGG", "연방헌법재판소법"],
  },
  {
    slug: "bloc-de-constitutionnalite",
    term: "Bloc de constitutionnalite",
    koreanTerm: "헌법성 블록",
    definition: "프랑스 헌법위원회가 합헌성 심사의 기준으로 삼는 1958년 헌법, 1789년 인권선언, 1946년 헌법 전문 등 헌법적 규범 묶음이다.",
    jurisdiction: "France",
    relatedTags: ["Bloc de constitutionnalite", "헌법성 블록", "Déclaration de 1789"],
  },
  {
    slug: "campaign-accounts",
    term: "Comptes de campagne",
    koreanTerm: "선거회계",
    definition: "후보자 또는 선거 캠프가 선거운동 수입과 지출을 기록해 제출하는 회계 자료로, 프랑스 선거 사건에서 당선 무효나 피선거권 제한과 연결될 수 있다.",
    jurisdiction: "France",
    relatedTags: ["회계보고서", "선거비용", "Comptes de campagne"],
  },
  {
    slug: "certiorari",
    term: "Writ of certiorari",
    koreanTerm: "사건심리명령",
    definition: "미국 연방대법원이 하급심 사건을 심리 대상으로 받아들일지 결정하는 절차적 장치다.",
    jurisdiction: "United States",
    relatedTags: ["Certiorari", "Supreme Court"],
  },
  {
    slug: "cnccfp",
    term: "Commission nationale des comptes de campagne et des financements politiques",
    koreanTerm: "프랑스 선거회계·정치자금위원회",
    definition: "프랑스 선거비용과 정치자금 회계를 심사하는 기관으로, 선거비용 초과나 회계보고서 문제를 헌법위원회에 연결하는 역할을 한다.",
    jurisdiction: "France",
    relatedTags: ["CNCCFP", "Commission nationale des comptes de campagne et des financements politiques"],
  },
  {
    slug: "code-electoral",
    term: "Code electoral",
    koreanTerm: "프랑스 선거법전",
    definition: "프랑스 선거 절차, 선거비용, 후보자 자격, 선거무효 판단의 기준이 되는 법전이다.",
    jurisdiction: "France",
    relatedTags: ["Code électoral", "선거법"],
  },
  {
    slug: "compelled-speech",
    term: "Compelled speech",
    koreanTerm: "강제표현",
    definition: "국가가 개인이나 단체에게 특정 메시지를 말하거나 표시하도록 강제하는 상황으로, 미국 수정헌법 제1조 사건에서 자주 문제 된다.",
    jurisdiction: "United States",
    relatedTags: ["Compelled speech", "First Amendment"],
  },
  {
    slug: "concrete-review",
    term: "Konkrete Normenkontrolle",
    koreanTerm: "구체적 규범통제",
    definition: "법원이 재판 중 적용해야 할 법률의 위헌성이 문제 된 경우, 독일 연방헌법재판소에 심사를 제청하는 절차다.",
    jurisdiction: "Germany",
    relatedTags: ["Konkrete Normenkontrolle", "위헌법률심판"],
  },
  {
    slug: "conseil-constitutionnel",
    term: "Conseil constitutionnel",
    koreanTerm: "프랑스 헌법위원회",
    definition: "프랑스의 헌법재판기관으로, 사전적 법률심사, QPC, 대통령·의회 선거 관련 심사 등을 담당한다.",
    jurisdiction: "France",
    relatedTags: ["Conseil constitutionnel", "헌법위원회"],
  },
  {
    slug: "constitutional-complaint",
    term: "Verfassungsbeschwerde",
    koreanTerm: "헌법소원",
    definition: "독일에서 공권력 행사로 기본권이 침해되었다고 주장하는 개인 등이 연방헌법재판소에 제기할 수 있는 권리구제 절차다.",
    jurisdiction: "Germany",
    relatedTags: ["Verfassungsbeschwerde", "헌법소원", "기본권"],
  },
  {
    slug: "constitutional-review",
    term: "Constitutional review",
    koreanTerm: "헌법심사",
    definition: "법률, 국가작용, 선거 절차 등이 헌법에 맞는지 헌법재판기관 또는 법원이 판단하는 절차와 판단 작용이다.",
    jurisdiction: null,
    relatedTags: ["헌법심사", "위헌심사", "헌법재판"],
  },
  {
    slug: "constitution-1958",
    term: "Constitution du 4 octobre 1958",
    koreanTerm: "1958년 프랑스 헌법",
    definition: "프랑스 제5공화국의 헌법으로, 헌법위원회의 권한과 법률심사, QPC의 근거 조항을 포함한다.",
    jurisdiction: "France",
    relatedTags: ["Constitution", "1958년 헌법", "Article 61", "Article 61-1"],
  },
  {
    slug: "declaration-1789",
    term: "Declaration des droits de l'homme et du citoyen de 1789",
    koreanTerm: "1789년 인간과 시민의 권리선언",
    definition: "프랑스 헌법성 블록의 핵심 문서로, 자유, 평등, 재산권, 죄형법정주의 등 여러 기본권 심사의 기준이 된다.",
    jurisdiction: "France",
    relatedTags: ["Déclaration des droits de l'homme et du citoyen de 1789", "Déclaration de 1789"],
  },
  {
    slug: "defense-rights",
    term: "Rights of defence / Droits de la defense",
    koreanTerm: "방어권",
    definition: "형사·징계·행정 절차에서 당사자가 자신에게 불리한 주장과 증거에 대응할 기회를 보장받는 권리다.",
    jurisdiction: null,
    relatedTags: ["방어권", "적법절차"],
  },
  {
    slug: "due-process",
    term: "Due process",
    koreanTerm: "적법절차",
    definition: "국가가 생명, 자유, 재산에 영향을 미칠 때 공정한 절차와 법적 근거를 갖추어야 한다는 미국 헌법 원칙이다.",
    jurisdiction: "United States",
    relatedTags: ["Due Process", "Fifth Amendment", "Fourteenth Amendment", "적법절차"],
  },
  {
    slug: "election-nullification",
    term: "Election annulment",
    koreanTerm: "선거무효",
    definition: "선거 절차의 중대한 위법이나 결과에 영향을 미친 하자를 이유로 선거 결과의 효력을 부정하는 판단이다.",
    jurisdiction: null,
    relatedTags: ["선거무효", "선거 무효", "Annulation"],
  },
  {
    slug: "electoral-complaint",
    term: "Wahlprufungsbeschwerde",
    koreanTerm: "선거심사청구",
    definition: "독일에서 연방의회 선거의 유효성 심사와 관련해 연방헌법재판소에 제기되는 절차다.",
    jurisdiction: "Germany",
    relatedTags: ["Wahlprüfungsbeschwerde", "선거심사"],
  },
  {
    slug: "equal-protection",
    term: "Equal Protection Clause",
    koreanTerm: "평등보호 조항",
    definition: "미국 수정헌법 제14조의 조항으로, 주가 사람을 불합리하게 차별하지 않아야 한다는 평등심사의 근거다.",
    jurisdiction: "United States",
    relatedTags: ["Equal Protection", "Fourteenth Amendment", "평등"],
  },
  {
    slug: "equality-principle",
    term: "Equality principle",
    koreanTerm: "평등원칙",
    definition: "같은 것은 같게, 다른 것은 다르게 취급해야 하며 차별에는 합리적 이유나 더 엄격한 정당화가 필요하다는 헌법 원칙이다.",
    jurisdiction: null,
    relatedTags: ["평등원칙", "평등 원칙", "Gleichheitssatz"],
  },
  {
    slug: "facial-challenge",
    term: "Facial challenge",
    koreanTerm: "문면 위헌 주장",
    definition: "특정 적용 사례가 아니라 법률 문언 자체가 헌법에 어긋난다고 다투는 미국 헌법소송의 주장 방식이다.",
    jurisdiction: "United States",
    relatedTags: ["Facial challenge", "위헌심사"],
  },
  {
    slug: "fifth-amendment",
    term: "Fifth Amendment",
    koreanTerm: "수정헌법 제5조",
    definition: "연방정부에 대한 적법절차, 자기부죄거부, 이중처벌 금지, 수용보상 등 여러 권리 보장의 근거가 되는 미국 헌법 조항이다.",
    jurisdiction: "United States",
    relatedTags: ["Fifth Amendment", "Due Process"],
  },
  {
    slug: "first-amendment",
    term: "First Amendment",
    koreanTerm: "수정헌법 제1조",
    definition: "표현, 언론, 종교, 집회, 청원의 자유를 보장하는 미국 헌법 조항이다.",
    jurisdiction: "United States",
    relatedTags: ["First Amendment", "표현의 자유", "Free Speech"],
  },
  {
    slug: "fourteenth-amendment",
    term: "Fourteenth Amendment",
    koreanTerm: "수정헌법 제14조",
    definition: "주에 대한 적법절차와 평등보호 원칙의 핵심 근거가 되는 미국 헌법 조항이다.",
    jurisdiction: "United States",
    relatedTags: ["Fourteenth Amendment", "Equal Protection", "Due Process"],
  },
  {
    slug: "freedom-of-expression",
    term: "Freedom of expression / Meinungsfreiheit / Liberte d'expression",
    koreanTerm: "표현의 자유",
    definition: "의견, 정보, 사상, 정치적 표현을 자유롭게 형성하고 전달할 수 있는 기본권으로, 민주적 의사형성의 핵심 조건이다.",
    jurisdiction: null,
    relatedTags: ["표현의 자유", "Free Speech", "Meinungsfreiheit"],
  },
  {
    slug: "grundgesetz",
    term: "Grundgesetz",
    koreanTerm: "독일 기본법",
    definition: "독일 연방공화국의 헌법으로, 기본권과 국가조직, 연방질서, 헌법재판의 기준을 담고 있다.",
    jurisdiction: "Germany",
    relatedTags: ["Grundgesetz", "독일 기본법"],
  },
  {
    slug: "human-dignity",
    term: "Menschenwurde / Human dignity",
    koreanTerm: "인간의 존엄",
    definition: "인간을 단순한 수단으로 취급해서는 안 된다는 독일 기본법 제1조의 핵심 가치이자 여러 기본권 해석의 출발점이다.",
    jurisdiction: "Germany",
    relatedTags: ["Menschenwürde", "Human dignity", "독일 기본법"],
  },
  {
    slug: "inadmissibility",
    term: "Inadmissibility / Irrecevabilite",
    koreanTerm: "각하",
    definition: "청구가 기간, 권리보호이익, 보충성, 관할 등 절차 요건을 충족하지 못해 본안 판단 없이 배척되는 결론이다.",
    jurisdiction: null,
    relatedTags: ["각하", "적법요건"],
  },
  {
    slug: "ineligibility",
    term: "Ineligibilite",
    koreanTerm: "피선거권 박탈",
    definition: "선거법 위반, 회계보고 문제, 법정 요건 미충족 등으로 일정 기간 선거에 후보자로 나설 자격을 제한하는 제재다.",
    jurisdiction: "France",
    relatedTags: ["피선거권 박탈", "피선거권", "Inéligibilité"],
  },
  {
    slug: "interim-measures",
    term: "Interim measures / Einstweilige Anordnung",
    koreanTerm: "가처분",
    definition: "본안 결정 전 중대한 손해를 막거나 현상 유지를 위해 잠정적으로 명령하는 절차다.",
    jurisdiction: null,
    relatedTags: ["가처분", "Einstweilige Anordnung"],
  },
  {
    slug: "intermediate-scrutiny",
    term: "Intermediate scrutiny",
    koreanTerm: "중간심사",
    definition: "미국 헌법심사에서 중요한 정부 이익과 그 이익에 실질적으로 관련된 수단을 요구하는 심사 강도다.",
    jurisdiction: "United States",
    relatedTags: ["Intermediate scrutiny", "심사기준"],
  },
  {
    slug: "jurisdiction",
    term: "Jurisdiction / Competence",
    koreanTerm: "관할권",
    definition: "특정 기관이나 법원이 어떤 사건을 심리하고 판단할 수 있는 권한 범위를 뜻한다.",
    jurisdiction: null,
    relatedTags: ["관할권", "Competence"],
  },
  {
    slug: "mootness",
    term: "Mootness",
    koreanTerm: "소의 이익 소멸",
    definition: "미국 연방법원에서 분쟁이 더 이상 현실적 의미를 갖지 않아 법원이 판단할 수 없게 되는 사법심사 제한 원칙이다.",
    jurisdiction: "United States",
    relatedTags: ["Mootness", "Article III"],
  },
  {
    slug: "non-admission",
    term: "Non-admission / Nichtannahme",
    koreanTerm: "불수리",
    definition: "헌법재판기관이 사건을 본안 심리 대상으로 받아들이지 않는 결정으로, 독일 헌법소원 등에서 자주 보인다.",
    jurisdiction: "Germany",
    relatedTags: ["불수리", "Nichtannahme", "헌법소원"],
  },
  {
    slug: "organic-law",
    term: "Loi organique",
    koreanTerm: "조직법",
    definition: "프랑스에서 헌법이 예정한 국가기관 구성과 권한, 선거·의회 운영 등을 구체화하는 특별한 법률 유형이다.",
    jurisdiction: "France",
    relatedTags: ["Loi organique", "조직법"],
  },
  {
    slug: "organ-dispute",
    term: "Organstreitverfahren",
    koreanTerm: "기관쟁의",
    definition: "독일에서 연방기관 또는 그 일부가 헌법상 권한과 의무를 둘러싸고 다투는 헌법재판 절차다.",
    jurisdiction: "Germany",
    relatedTags: ["Organstreitverfahren", "기관쟁의"],
  },
  {
    slug: "overbreadth",
    term: "Overbreadth doctrine",
    koreanTerm: "과잉광범성 원칙",
    definition: "미국 표현의 자유 사건에서 법률이 금지할 수 있는 영역을 넘어 보호되는 표현까지 지나치게 넓게 제한할 때 문제 되는 원칙이다.",
    jurisdiction: "United States",
    relatedTags: ["Overbreadth", "First Amendment"],
  },
  {
    slug: "political-finance",
    term: "Political finance",
    koreanTerm: "정치자금",
    definition: "정당, 후보자, 선거운동의 자금 조달과 지출에 관한 규율 영역으로, 선거 공정성과 표현·참여의 자유가 함께 문제 된다.",
    jurisdiction: null,
    relatedTags: ["정치자금", "선거비용", "Political finance"],
  },
  {
    slug: "prior-restraint",
    term: "Prior restraint",
    koreanTerm: "사전억제",
    definition: "표현이 이루어지기 전에 국가가 허가, 금지, 검열로 표현을 막는 조치로, 미국 수정헌법 제1조상 특히 엄격하게 심사된다.",
    jurisdiction: "United States",
    relatedTags: ["Prior restraint", "First Amendment", "표현의 자유"],
  },
  {
    slug: "property-right",
    term: "Property right",
    koreanTerm: "재산권",
    definition: "재산의 사용, 수익, 처분에 대한 헌법상 보호로, 수용, 규제, 조세, 몰수 사건에서 제한의 정당성이 문제 된다.",
    jurisdiction: null,
    relatedTags: ["재산권", "Property", "Fifth Amendment"],
  },
  {
    slug: "proportionality",
    term: "Proportionality",
    koreanTerm: "비례원칙",
    definition: "기본권 제한이 목적의 정당성, 수단의 적합성, 최소침해성, 법익균형을 충족해야 한다는 심사 구조다.",
    jurisdiction: null,
    relatedTags: ["비례원칙", "Proportionality"],
  },
  {
    slug: "qpc",
    term: "Question prioritaire de constitutionnalite",
    koreanTerm: "우선적 위헌심사절차",
    definition: "프랑스에서 재판 계속 중 법률 조항의 헌법합치성을 사후적으로 다투는 절차다.",
    jurisdiction: "France",
    relatedTags: ["QPC", "Article 61-1", "우선적 위헌심사"],
  },
  {
    slug: "rational-basis-review",
    term: "Rational basis review",
    koreanTerm: "합리성 심사",
    definition: "미국 헌법심사에서 정부 목적이 정당하고 수단이 그 목적과 합리적으로 관련되면 통과하는 가장 완화된 심사 기준이다.",
    jurisdiction: "United States",
    relatedTags: ["Rational basis", "Equal Protection"],
  },
  {
    slug: "reserve-dinterpretation",
    term: "Reserve d'interpretation",
    koreanTerm: "합헌적 해석유보",
    definition: "프랑스 헌법위원회가 법률 조항을 특정한 방식으로 해석하는 한 합헌이라고 선언하는 판단 방식이다.",
    jurisdiction: "France",
    relatedTags: ["Réserve d'interprétation", "합헌적 해석"],
  },
  {
    slug: "right-to-be-heard",
    term: "Rechtliches Gehor",
    koreanTerm: "진술청취권",
    definition: "법원이 당사자의 주장과 의견을 들을 기회를 보장해야 한다는 독일 기본권적 절차 보장이다.",
    jurisdiction: "Germany",
    relatedTags: ["Rechtliches Gehör", "청문권", "재판청구권"],
  },
  {
    slug: "right-to-court",
    term: "Right of access to court",
    koreanTerm: "재판청구권",
    definition: "권리 침해를 주장하는 사람이 독립된 법원 또는 재판기관에 접근해 판단을 받을 수 있는 절차적 기본권이다.",
    jurisdiction: null,
    relatedTags: ["재판청구권", "Access to court"],
  },
  {
    slug: "ripeness",
    term: "Ripeness",
    koreanTerm: "성숙성",
    definition: "미국 연방법원에서 분쟁이 아직 충분히 현실화되지 않았으면 판단하지 않는 사법심사 제한 원칙이다.",
    jurisdiction: "United States",
    relatedTags: ["Ripeness", "Article III"],
  },
  {
    slug: "rule-of-law",
    term: "Rule of law / Rechtsstaat",
    koreanTerm: "법치주의",
    definition: "국가권력이 법에 근거하고, 예측 가능하며, 기본권과 권력분립의 한계 안에서 행사되어야 한다는 헌법 원리다.",
    jurisdiction: null,
    relatedTags: ["법치주의", "Rechtsstaat", "Rule of law"],
  },
  {
    slug: "separation-of-powers",
    term: "Separation of powers",
    koreanTerm: "권력분립",
    definition: "입법, 행정, 사법 권한을 분산하고 상호 견제하게 하여 권력 집중과 자의적 국가작용을 막는 헌법 원리다.",
    jurisdiction: null,
    relatedTags: ["권력분립", "Separation of powers"],
  },
  {
    slug: "sincerite-du-scrutin",
    term: "Sincerite du scrutin",
    koreanTerm: "선거의 진정성",
    definition: "프랑스 선거심사에서 선거 과정의 위법이 유권자의 자유로운 의사와 결과의 신뢰성을 해쳤는지 판단하는 기준이다.",
    jurisdiction: "France",
    relatedTags: ["Sincérité du scrutin", "선거무효", "프랑스 선거"],
  },
  {
    slug: "standing",
    term: "Standing",
    koreanTerm: "당사자적격",
    definition: "미국 연방법원에서 원고가 구체적 손해, 인과관계, 구제가능성을 보여야 본안 판단을 받을 수 있다는 사법심사 요건이다.",
    jurisdiction: "United States",
    relatedTags: ["Standing", "Article III", "당사자적격"],
  },
  {
    slug: "strict-scrutiny",
    term: "Strict scrutiny",
    koreanTerm: "엄격심사",
    definition: "중요한 기본권 제한이나 의심스러운 차별에 대해 중대한 정부 이익과 엄밀하게 맞춘 수단을 요구하는 미국 헌법심사 기준이다.",
    jurisdiction: "United States",
    relatedTags: ["Strict scrutiny", "Equal Protection", "First Amendment"],
  },
  {
    slug: "subsidiarity",
    term: "Subsidiarity / Subsidiaritat",
    koreanTerm: "보충성 원칙",
    definition: "헌법재판을 청구하기 전에 가능한 일반 법적 구제수단을 먼저 사용해야 한다는 절차 원칙이다.",
    jurisdiction: "Germany",
    relatedTags: ["보충성 원칙", "Subsidiarität", "헌법소원"],
  },
];
