-- WorldCons D1 schema: worldcons_ops
-- LOCAL ONLY. Generated by "pnpm d1:schema --emit".
-- Do not create a remote database or deploy from this milestone (plan M5, no authority switch).

create table if not exists admin_article_edit_history (
  id text not null,
  article_id text not null,
  article_slug text,
  edited_at text not null,
  actor_id text,
  changed_fields text not null default '{}',
  previous_summary_hash text,
  next_summary_hash text,
  diff_redacted text not null default '{}',
  primary key (id)
);

create table if not exists admin_audit_logs (
  id text not null,
  occurred_at text not null,
  actor_id text,
  actor_role text default 'admin',
  action text not null,
  target_type text,
  target_id text,
  article_id text,
  article_slug text,
  source_key text,
  job_id text,
  result text,
  error_class text,
  redacted_metadata text not null default '{}',
  request_ip_hash text,
  user_agent_family text,
  primary key (id)
);

create table if not exists admin_job_events (
  id text not null,
  job_id text not null,
  occurred_at text not null,
  event_type text not null,
  message text,
  error_class text,
  metadata text not null default '{}',
  primary key (id)
);

create table if not exists admin_jobs (
  id text not null,
  job_type text not null,
  status text not null default 'queued',
  priority integer not null default 0,
  source_key text,
  article_id text,
  article_slug text,
  idempotency_key text not null,
  requested_by text,
  requested_at text not null,
  started_at text,
  finished_at text,
  lease_until text,
  worker_id text,
  progress_current integer not null default 0,
  progress_total integer,
  result_summary text not null default '{}',
  error_class text,
  error_message text,
  cancel_requested_at text,
  cancelled_at text,
  cancel_reason text,
  parent_job_id text,
  options text not null default '{}',
  created_at text not null,
  updated_at text not null,
  primary key (id)
);
create unique index if not exists admin_jobs_idempotency_key_key on admin_jobs (idempotency_key);

create table if not exists llm_settings (
  id text not null,
  settings text not null default '{}',
  created_at text not null,
  updated_at text not null,
  primary key (id)
);

create table if not exists site_events (
  id text not null,
  occurred_at text not null,
  event_type text not null check (event_type in ('page_view', 'article_view', 'search', 'tag_click', 'tag_view', 'source_view', 'article_click', 'external_link_click', 'security_event', 'admin_action', 'admin_review_action')),
  path text,
  article_id text,
  article_slug text,
  article_title text,
  tag_slug text,
  tag_name text,
  source_key text,
  jurisdiction text,
  institution_name text,
  search_query text,
  search_mode text,
  result_count integer,
  referrer_host text,
  user_agent_family text,
  device_type text,
  metadata text not null default '{}',
  client_ip_hash text,
  accept_language text,
  client_country text,
  is_bot integer not null default 0,
  primary key (id)
);
