begin;

-- Gate 1 blob contract (M1): additive externalization columns, transition-state
-- constraints, an append-only externalization ledger, and record RPC v2.
-- Existing v1 RPCs stay in place and keep their exact signature and behavior.
-- No destructive schema or data changes; fetch/normalize payloads are only
-- relocated by later milestones.

alter table source_fetch_artifacts
  add column if not exists bounded_replay_storage_ref text,
  add column if not exists externalized_at timestamptz,
  add column if not exists externalization_contract_version text;

alter table source_normalization_artifacts
  add column if not exists normalized_output_storage_ref text,
  add column if not exists normalized_output_size bigint,
  add column if not exists externalized_at timestamptz,
  add column if not exists externalization_contract_version text;

alter table source_fetch_artifacts drop constraint if exists source_fetch_artifacts_replay_check;
alter table source_fetch_artifacts add constraint source_fetch_artifacts_replay_check check (
  (replayability = 'full_snapshot' and immutable_storage_ref is not null
    and bounded_replay_payload is null and bounded_replay_storage_ref is null)
  or (replayability = 'bounded_evidence' and immutable_storage_ref is null
    and (bounded_replay_payload is not null or bounded_replay_storage_ref is not null))
  or (replayability = 'non_replayable' and immutable_storage_ref is null
    and bounded_replay_payload is null and bounded_replay_storage_ref is null)
);

alter table source_fetch_artifacts drop constraint if exists source_fetch_artifacts_bounded_replay_ref_check;
alter table source_fetch_artifacts add constraint source_fetch_artifacts_bounded_replay_ref_check check (
  bounded_replay_storage_ref is null
  or (
    length(bounded_replay_storage_ref) between 1 and 500
    and bounded_replay_storage_ref ~ '^artifacts/fetch/[a-z][a-z0-9._-]{0,79}/[0-9a-f]{64}\.json$'
    and bounded_replay_storage_ref !~* '(token|secret|signature|credential)'
  )
);

alter table source_fetch_artifacts drop constraint if exists source_fetch_artifacts_externalization_contract_check;
alter table source_fetch_artifacts add constraint source_fetch_artifacts_externalization_contract_check check (
  (
    externalized_at is null
    and externalization_contract_version is null
    and bounded_replay_storage_ref is null
  )
  or (
    externalized_at is not null
    and externalization_contract_version is not null
    and length(externalization_contract_version) between 1 and 120
    and bounded_replay_storage_ref is not null
  )
);

alter table source_normalization_artifacts drop constraint if exists source_normalization_artifacts_json_check;
alter table source_normalization_artifacts add constraint source_normalization_artifacts_json_check check (
  jsonb_typeof(validation_errors) = 'array' and pg_column_size(validation_errors) <= 32768
  and (
    (jsonb_typeof(normalized_output) = 'object' and pg_column_size(normalized_output) <= 4194304)
    or (normalized_output is null and normalized_output_storage_ref is not null)
  )
);

alter table source_normalization_artifacts drop constraint if exists source_normalization_artifacts_output_size_check;
alter table source_normalization_artifacts add constraint source_normalization_artifacts_output_size_check check (
  normalized_output_size is null
  or (normalized_output_size between 0 and 4194304
    and normalized_output_storage_ref is not null)
);

alter table source_normalization_artifacts drop constraint if exists source_normalization_artifacts_output_ref_check;
alter table source_normalization_artifacts add constraint source_normalization_artifacts_output_ref_check check (
  normalized_output_storage_ref is null
  or (
    length(normalized_output_storage_ref) between 1 and 500
    and normalized_output_storage_ref ~ '^artifacts/normalization/[a-z][a-z0-9._-]{0,79}/[0-9a-f]{64}\.json$'
    and normalized_output_storage_ref !~* '(token|secret|signature|credential)'
  )
);

alter table source_normalization_artifacts drop constraint if exists source_normalization_artifacts_externalization_contract_check;
alter table source_normalization_artifacts add constraint source_normalization_artifacts_externalization_contract_check check (
  (
    externalized_at is null
    and externalization_contract_version is null
    and normalized_output_storage_ref is null
    and normalized_output_size is null
  )
  or (
    externalized_at is not null
    and externalization_contract_version is not null
    and length(externalization_contract_version) between 1 and 120
    and normalized_output_storage_ref is not null
    and normalized_output_size is not null
  )
);

create table if not exists source_artifact_externalization_ledger (
  id bigint generated by default as identity primary key,
  artifact_table text not null,
  artifact_id uuid not null,
  item_id uuid,
  content_kind text not null,
  storage_ref text not null,
  content_hash text not null,
  content_size bigint not null,
  externalization_contract_version text not null,
  actor_type text not null,
  actor_id text,
  externalized_at timestamptz not null default now(),
  constraint source_artifact_externalization_ledger_table_check check (
    artifact_table in ('source_fetch_artifacts', 'source_normalization_artifacts')
  ),
  constraint source_artifact_externalization_ledger_kind_check check (
    (artifact_table = 'source_fetch_artifacts' and content_kind = 'bounded_replay_payload')
    or (artifact_table = 'source_normalization_artifacts' and content_kind = 'normalized_output')
  ),
  constraint source_artifact_externalization_ledger_hash_check check (
    content_hash ~ '^[0-9a-f]{64}$'
  ),
  constraint source_artifact_externalization_ledger_size_check check (
    content_size between 0 and 4194304
  ),
  constraint source_artifact_externalization_ledger_ref_check check (
    (
      (content_kind = 'bounded_replay_payload'
        and storage_ref ~ '^artifacts/fetch/[a-z][a-z0-9._-]{0,79}/[0-9a-f]{64}\.json$')
      or (content_kind = 'normalized_output'
        and storage_ref ~ '^artifacts/normalization/[a-z][a-z0-9._-]{0,79}/[0-9a-f]{64}\.json$')
    )
    and length(storage_ref) between 1 and 500
    and storage_ref !~* '(token|secret|signature|credential)'
  ),
  constraint source_artifact_externalization_ledger_contract_check check (
    length(externalization_contract_version) between 1 and 120
  ),
  constraint source_artifact_externalization_ledger_actor_check check (
    actor_type in ('service', 'operator')
    and (actor_id is null or length(actor_id) between 1 and 160)
  )
);

create unique index if not exists source_artifact_externalization_ledger_unique_idx
  on source_artifact_externalization_ledger(artifact_table, artifact_id, externalization_contract_version);
create index if not exists source_artifact_externalization_ledger_item_idx
  on source_artifact_externalization_ledger(item_id, externalized_at desc);

drop trigger if exists source_artifact_externalization_ledger_immutable_trigger on source_artifact_externalization_ledger;
create trigger source_artifact_externalization_ledger_immutable_trigger
before update or delete on source_artifact_externalization_ledger
for each row execute function case_backfill_prevent_mutation_v1();

create or replace function source_backfill_fetch_artifact_record_v2(
  p_item_id uuid,
  p_p1_attempt_id uuid,
  p_p1_fencing_token bigint,
  p_source_policy_version text,
  p_authority_url text,
  p_http_status integer,
  p_response_headers jsonb,
  p_source_etag text,
  p_source_last_modified_at timestamptz,
  p_payload_hash text,
  p_payload_size bigint,
  p_replayability text,
  p_immutable_storage_ref text,
  p_bounded_replay_payload jsonb,
  p_bounded_replay_storage_ref text,
  p_fetch_contract_version text,
  p_externalization_contract_version text
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
  v_item source_backfill_items%rowtype;
  v_id uuid;
  v_payload_ref text;
  v_externalization_version text;
begin
  select i.* into v_item from source_backfill_items i where i.id = p_item_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'CASE_BACKFILL_ITEM_NOT_FOUND'; end if;
  perform source_backfill_assert_attempt_v1(p_p1_attempt_id, p_p1_fencing_token, v_item.snapshot_id, 'fetch');
  if v_item.claimed_attempt_id <> p_p1_attempt_id or v_item.claimed_fencing_token <> p_p1_fencing_token
    or v_item.claimed_phase <> 'fetch' or v_item.lease_expires_at <= now()
  then raise exception using errcode = '40001', message = 'CASE_BACKFILL_ITEM_LEASE_LOST'; end if;

  v_payload_ref := nullif(trim(coalesce(p_bounded_replay_storage_ref, '')), '');
  if v_payload_ref is null then
    v_externalization_version := null;
  else
    v_externalization_version := nullif(trim(coalesce(p_externalization_contract_version, '')), '');
    if v_externalization_version is null then
      raise exception using errcode = '22023', message = 'CASE_BACKFILL_EXTERNALIZATION_CONTRACT_REQUIRED';
    end if;
  end if;

  insert into source_fetch_artifacts(
    item_id, source_policy_version, authority_url, http_status, response_headers_allowlist,
    source_etag, source_last_modified_at, payload_hash, payload_size, replayability,
    immutable_storage_ref, bounded_replay_payload, bounded_replay_storage_ref,
    externalized_at, externalization_contract_version, fetch_contract_version
  ) values (
    v_item.id, p_source_policy_version, p_authority_url, p_http_status, coalesce(p_response_headers, '{}'::jsonb),
    nullif(trim(p_source_etag), ''), p_source_last_modified_at, p_payload_hash, p_payload_size, p_replayability,
    nullif(trim(p_immutable_storage_ref), ''), p_bounded_replay_payload, v_payload_ref,
    case when v_payload_ref is null then null else now() end, v_externalization_version, p_fetch_contract_version
  )
  on conflict (item_id, payload_hash, fetch_contract_version) do nothing
  returning id into v_id;
  if v_id is null then
    select f.id into v_id from source_fetch_artifacts f
    where f.item_id = v_item.id and f.payload_hash = p_payload_hash and f.fetch_contract_version = p_fetch_contract_version;
  end if;

  insert into source_backfill_item_events(item_id, attempt_id, event_type, phase, safe_details)
  values (v_item.id, p_p1_attempt_id, 'fetch_recorded', 'fetch',
    jsonb_build_object('artifactId', v_id, 'payloadHash', p_payload_hash));
  return v_id;
end;
$function$;

create or replace function source_backfill_normalization_artifact_record_v2(
  p_item_id uuid,
  p_p1_attempt_id uuid,
  p_p1_fencing_token bigint,
  p_fetch_artifact_id uuid,
  p_parser_version text,
  p_normalization_contract_version text,
  p_normalized_output jsonb,
  p_normalized_output_hash text,
  p_normalized_output_storage_ref text,
  p_normalized_output_size bigint,
  p_validation_status text,
  p_validation_errors jsonb,
  p_externalization_contract_version text
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
  v_item source_backfill_items%rowtype;
  v_id uuid;
  v_output_ref text;
  v_externalization_version text;
begin
  select i.* into v_item from source_backfill_items i where i.id = p_item_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'CASE_BACKFILL_ITEM_NOT_FOUND'; end if;
  perform source_backfill_assert_attempt_v1(p_p1_attempt_id, p_p1_fencing_token, v_item.snapshot_id, 'normalize');
  if v_item.claimed_attempt_id <> p_p1_attempt_id or v_item.claimed_fencing_token <> p_p1_fencing_token
    or v_item.claimed_phase <> 'normalize' or v_item.lease_expires_at <= now()
    or v_item.current_fetch_artifact_id is distinct from p_fetch_artifact_id
  then raise exception using errcode = '40001', message = 'CASE_BACKFILL_ITEM_LEASE_LOST'; end if;

  v_output_ref := nullif(trim(coalesce(p_normalized_output_storage_ref, '')), '');
  if v_output_ref is null then
    if p_normalized_output_size is not null then
      raise exception using errcode = '22023', message = 'CASE_BACKFILL_NORMALIZED_OUTPUT_REF_REQUIRED';
    end if;
    v_externalization_version := null;
  else
    if p_normalized_output_size is null or p_normalized_output_size < 0 then
      raise exception using errcode = '22023', message = 'CASE_BACKFILL_NORMALIZED_OUTPUT_SIZE_REQUIRED';
    end if;
    v_externalization_version := nullif(trim(coalesce(p_externalization_contract_version, '')), '');
    if v_externalization_version is null then
      raise exception using errcode = '22023', message = 'CASE_BACKFILL_EXTERNALIZATION_CONTRACT_REQUIRED';
    end if;
  end if;

  insert into source_normalization_artifacts(
    item_id, fetch_artifact_id, parser_version, normalization_contract_version,
    normalized_output, normalized_output_hash, normalized_output_storage_ref, normalized_output_size,
    validation_status, validation_errors, externalized_at, externalization_contract_version
  ) values (
    v_item.id, p_fetch_artifact_id, p_parser_version, p_normalization_contract_version,
    p_normalized_output, p_normalized_output_hash, v_output_ref, p_normalized_output_size,
    p_validation_status, coalesce(p_validation_errors, '[]'::jsonb),
    case when v_output_ref is null then null else now() end, v_externalization_version
  )
  on conflict (fetch_artifact_id, parser_version, normalization_contract_version) do nothing
  returning id into v_id;
  if v_id is null then
    select n.id into v_id from source_normalization_artifacts n
    where n.fetch_artifact_id = p_fetch_artifact_id and n.parser_version = p_parser_version
      and n.normalization_contract_version = p_normalization_contract_version;
  end if;

  insert into source_backfill_item_events(item_id, attempt_id, event_type, phase, safe_details)
  values (v_item.id, p_p1_attempt_id, 'normalization_recorded', 'normalize',
    jsonb_build_object('artifactId', v_id, 'normalizedOutputHash', p_normalized_output_hash, 'validationStatus', p_validation_status));
  return v_id;
end;
$function$;

alter table source_artifact_externalization_ledger enable row level security;

revoke all on table source_artifact_externalization_ledger from public;
revoke all on function source_backfill_fetch_artifact_record_v2(uuid, uuid, bigint, text, text, integer, jsonb, text, timestamptz, text, bigint, text, text, jsonb, text, text, text) from public;
revoke all on function source_backfill_normalization_artifact_record_v2(uuid, uuid, bigint, uuid, text, text, jsonb, text, text, bigint, text, jsonb, text) from public;

do $permissions$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on table source_artifact_externalization_ledger from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all on table source_artifact_externalization_ledger from authenticated;
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select on table source_artifact_externalization_ledger to service_role;
    grant execute on function source_backfill_fetch_artifact_record_v2(uuid, uuid, bigint, text, text, integer, jsonb, text, timestamptz, text, bigint, text, text, jsonb, text, text, text) to service_role;
    grant execute on function source_backfill_normalization_artifact_record_v2(uuid, uuid, bigint, uuid, text, text, jsonb, text, text, bigint, text, jsonb, text) to service_role;
  end if;
end;
$permissions$;

comment on table source_artifact_externalization_ledger is
  'Append-only audit ledger recording private Blob externalization of fetch and normalization payloads; stores stable object refs and SHA-256 only.';
comment on column source_fetch_artifacts.bounded_replay_storage_ref is
  'Content-addressed private Blob object key for the bounded replay payload.';
comment on column source_normalization_artifacts.normalized_output_storage_ref is
  'Content-addressed private Blob object key for the normalized output document.';
comment on column source_normalization_artifacts.normalized_output_size is
  'Exact byte size of the externalized normalized output document.';
comment on function source_backfill_fetch_artifact_record_v2(uuid, uuid, bigint, text, text, integer, jsonb, text, timestamptz, text, bigint, text, text, jsonb, text, text, text) is
  'Fetch artifact record RPC v2: identical fencing to v1 plus optional externalized bounded replay storage ref.';
comment on function source_backfill_normalization_artifact_record_v2(uuid, uuid, bigint, uuid, text, text, jsonb, text, text, bigint, text, jsonb, text) is
  'Normalization artifact record RPC v2: identical fencing to v1 plus optional externalized normalized output ref and size.';

commit;
