begin;

create table if not exists source_inventory_snapshot_supersessions (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null unique references source_inventory_snapshots(id) on delete restrict,
  source_key text not null,
  source_policy_version text not null,
  prior_parser_version text not null,
  replacement_parser_version text not null,
  prior_manifest_hash text not null,
  prior_enumeration_manifest_hash text not null,
  discovered_count integer not null,
  reason_code text not null,
  requested_by text not null,
  superseded_at timestamptz not null default clock_timestamp(),
  constraint source_inventory_snapshot_supersessions_policy_fkey
    foreign key (source_key, source_policy_version)
    references source_corpus_policies(source_key, policy_version) on delete restrict,
  constraint source_inventory_snapshot_supersessions_hash_check check (
    prior_manifest_hash ~ '^[0-9a-f]{64}$'
    and prior_enumeration_manifest_hash ~ '^[0-9a-f]{64}$'
  ),
  constraint source_inventory_snapshot_supersessions_count_check check (discovered_count >= 0),
  constraint source_inventory_snapshot_supersessions_parser_check check (
    length(prior_parser_version) between 1 and 120
    and length(replacement_parser_version) between 1 and 120
    and replacement_parser_version <> prior_parser_version
  ),
  constraint source_inventory_snapshot_supersessions_reason_check check (
    reason_code ~ '^[a-z][a-z0-9._-]{2,79}$'
    and length(requested_by) between 1 and 160
  )
);

drop trigger if exists source_inventory_snapshot_supersessions_immutable_trigger
  on source_inventory_snapshot_supersessions;
create trigger source_inventory_snapshot_supersessions_immutable_trigger
before update or delete on source_inventory_snapshot_supersessions
for each row execute function case_backfill_prevent_mutation_v1();

create or replace function source_inventory_snapshot_supersede_v1(
  p_snapshot_id uuid,
  p_expected_manifest_hash text,
  p_expected_enumeration_manifest_hash text,
  p_expected_discovered_count integer,
  p_replacement_parser_version text,
  p_reason_code text,
  p_requested_by text
)
returns table(
  snapshot_id uuid,
  source_key text,
  prior_parser_version text,
  replacement_parser_version text,
  manifest_hash text,
  enumeration_manifest_hash text,
  discovered_count integer,
  reason_code text,
  requested_by text,
  superseded_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
  v_snapshot source_inventory_snapshots%rowtype;
  v_audit source_inventory_snapshot_supersessions%rowtype;
  v_item_count integer;
begin
  if p_snapshot_id is null
    or p_expected_manifest_hash !~ '^[0-9a-f]{64}$'
    or p_expected_enumeration_manifest_hash !~ '^[0-9a-f]{64}$'
    or p_expected_discovered_count is null or p_expected_discovered_count < 0
    or p_replacement_parser_version is null
    or length(trim(p_replacement_parser_version)) not between 1 and 120
    or p_reason_code is null or trim(p_reason_code) !~ '^[a-z][a-z0-9._-]{2,79}$'
    or p_requested_by is null or length(trim(p_requested_by)) not between 1 and 160
  then
    raise exception using errcode = '22023', message = 'CASE_BACKFILL_SUPERSESSION_INPUT_INVALID';
  end if;

  select s.* into v_snapshot
  from source_inventory_snapshots s
  where s.id = p_snapshot_id
  for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'CASE_BACKFILL_SNAPSHOT_NOT_FOUND';
  end if;

  if v_snapshot.status = 'superseded' then
    select a.* into v_audit
    from source_inventory_snapshot_supersessions a
    where a.snapshot_id = v_snapshot.id;
    if not found
      or v_audit.prior_manifest_hash is distinct from p_expected_manifest_hash
      or v_audit.prior_enumeration_manifest_hash is distinct from p_expected_enumeration_manifest_hash
      or v_audit.discovered_count is distinct from p_expected_discovered_count
      or v_audit.replacement_parser_version is distinct from trim(p_replacement_parser_version)
      or v_audit.reason_code is distinct from trim(p_reason_code)
      or v_audit.requested_by is distinct from trim(p_requested_by)
    then
      raise exception using errcode = '23505', message = 'CASE_BACKFILL_SUPERSESSION_CONFLICT';
    end if;
    return query select
      v_snapshot.id, v_audit.source_key, v_audit.prior_parser_version,
      v_audit.replacement_parser_version, v_audit.prior_manifest_hash,
      v_audit.prior_enumeration_manifest_hash, v_audit.discovered_count,
      v_audit.reason_code, v_audit.requested_by, v_audit.superseded_at;
    return;
  end if;

  if v_snapshot.status <> 'closed' then
    raise exception using errcode = '55000', message = 'CASE_BACKFILL_SUPERSESSION_REQUIRES_CLOSED_SNAPSHOT';
  end if;
  if v_snapshot.manifest_hash is distinct from p_expected_manifest_hash
    or v_snapshot.enumeration_manifest_hash is distinct from p_expected_enumeration_manifest_hash
    or v_snapshot.discovered_count is distinct from p_expected_discovered_count
  then
    raise exception using errcode = '40001', message = 'CASE_BACKFILL_SUPERSESSION_CAS_MISMATCH';
  end if;
  if v_snapshot.parser_version = trim(p_replacement_parser_version) then
    raise exception using errcode = '22023', message = 'CASE_BACKFILL_SUPERSESSION_PARSER_UNCHANGED';
  end if;

  select count(*)::integer into v_item_count
  from source_backfill_items i where i.snapshot_id = v_snapshot.id;
  if v_item_count <> v_snapshot.discovered_count then
    raise exception using errcode = '23514', message = 'CASE_BACKFILL_SUPERSESSION_ITEM_COUNT_MISMATCH';
  end if;
  if exists(
    select 1 from source_backfill_runs r
    where r.snapshot_id = v_snapshot.id and r.status in ('queued', 'running', 'deferred')
  ) then
    raise exception using errcode = '55000', message = 'CASE_BACKFILL_SUPERSESSION_ACTIVE_RUN';
  end if;
  if exists(
    select 1 from source_request_permits p
    where p.snapshot_id = v_snapshot.id
      and p.released_at is null
      and p.lease_expires_at > clock_timestamp()
  ) then
    raise exception using errcode = '55000', message = 'CASE_BACKFILL_SUPERSESSION_ACTIVE_PERMIT';
  end if;
  if exists(
    select 1 from source_backfill_items i
    where i.snapshot_id = v_snapshot.id and i.claimed_attempt_id is not null
  ) then
    raise exception using errcode = '55000', message = 'CASE_BACKFILL_SUPERSESSION_ACTIVE_CLAIM';
  end if;
  if exists(
    select 1 from source_backfill_runs r
    where r.snapshot_id = v_snapshot.id and r.phase <> 'discover'
  ) or exists(
    select 1 from source_backfill_items i
    where i.snapshot_id = v_snapshot.id and (
      i.status <> 'discovered'
      or i.authority_url is not null
      or i.current_fetch_artifact_id is not null
      or i.current_normalization_artifact_id is not null
      or i.verified_normalization_artifact_id is not null
      or i.published_normalization_artifact_id is not null
      or i.article_id is not null
      or i.next_attempt_at is not null
      or i.retry_phase is not null
    )
  ) or exists(
    select 1 from source_fetch_artifacts f
    join source_backfill_items i on i.id = f.item_id
    where i.snapshot_id = v_snapshot.id
  ) or exists(
    select 1 from source_normalization_artifacts n
    join source_backfill_items i on i.id = n.item_id
    where i.snapshot_id = v_snapshot.id
  ) or exists(
    select 1 from source_backfill_item_events e
    join source_backfill_items i on i.id = e.item_id
    where i.snapshot_id = v_snapshot.id and e.event_type <> 'item_discovered'
  ) then
    raise exception using errcode = '55000', message = 'CASE_BACKFILL_SUPERSESSION_PROCESSING_STARTED';
  end if;

  insert into source_inventory_snapshot_supersessions(
    snapshot_id, source_key, source_policy_version,
    prior_parser_version, replacement_parser_version,
    prior_manifest_hash, prior_enumeration_manifest_hash, discovered_count,
    reason_code, requested_by
  ) values (
    v_snapshot.id, v_snapshot.source_key, v_snapshot.source_policy_version,
    v_snapshot.parser_version, trim(p_replacement_parser_version),
    v_snapshot.manifest_hash, v_snapshot.enumeration_manifest_hash, v_snapshot.discovered_count,
    trim(p_reason_code), trim(p_requested_by)
  ) returning * into v_audit;

  update source_inventory_snapshots s
  set status = 'superseded'
  where s.id = v_snapshot.id and s.status = 'closed';
  if not found then
    raise exception using errcode = '40001', message = 'CASE_BACKFILL_SUPERSESSION_STATUS_RACE';
  end if;

  return query select
    v_snapshot.id, v_audit.source_key, v_audit.prior_parser_version,
    v_audit.replacement_parser_version, v_audit.prior_manifest_hash,
    v_audit.prior_enumeration_manifest_hash, v_audit.discovered_count,
    v_audit.reason_code, v_audit.requested_by, v_audit.superseded_at;
end;
$function$;

alter table source_inventory_snapshot_supersessions enable row level security;

revoke all on table source_inventory_snapshot_supersessions from public;
revoke all on function source_inventory_snapshot_supersede_v1(
  uuid, text, text, integer, text, text, text
) from public;

do $permissions$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    revoke all on table source_inventory_snapshot_supersessions from anon;
    revoke execute on function source_inventory_snapshot_supersede_v1(
      uuid, text, text, integer, text, text, text
    ) from anon;
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    revoke all on table source_inventory_snapshot_supersessions from authenticated;
    revoke execute on function source_inventory_snapshot_supersede_v1(
      uuid, text, text, integer, text, text, text
    ) from authenticated;
  end if;
  if exists(select 1 from pg_roles where rolname='service_role') then
    grant select on table source_inventory_snapshot_supersessions to service_role;
    grant execute on function source_inventory_snapshot_supersede_v1(
      uuid, text, text, integer, text, text, text
    ) to service_role;
  end if;
end;
$permissions$;

comment on table source_inventory_snapshot_supersessions is
  'Append-only audit ledger for CAS-protected replacement of sealed, discovery-only inventory snapshots.';
comment on function source_inventory_snapshot_supersede_v1(uuid,text,text,integer,text,text,text) is
  'Marks an untouched closed inventory superseded only after exact manifest CAS and fail-closed processing checks.';

commit;
