-- P5 operational governance. Additive and rerunnable; no legacy authority is removed.

create table if not exists admin_compatibility_observations_p5 (
  bucket_started_at timestamptz not null,
  surface text not null,
  domain text not null,
  direction text not null,
  authority text not null,
  outcome text not null,
  observation_count bigint not null default 0,
  unexplained_count bigint not null default 0,
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  primary key (bucket_started_at, surface, domain, direction, authority, outcome),
  constraint admin_compat_obs_p5_bucket_check check (bucket_started_at = date_trunc('hour', bucket_started_at)),
  constraint admin_compat_obs_p5_surface_check check (surface in ('admin_command', 'article_lifecycle', 'article_publication', 'public_query', 'vector_search', 'admin_dashboard', 'admin_analytics')),
  constraint admin_compat_obs_p5_domain_check check (domain in ('queue', 'lifecycle', 'publication', 'projection', 'operations')),
  constraint admin_compat_obs_p5_direction_check check (direction in ('read', 'write')),
  constraint admin_compat_obs_p5_authority_check check (authority in ('legacy', 'new', 'fallback')),
  constraint admin_compat_obs_p5_outcome_check check (outcome in ('selected', 'succeeded', 'failed', 'fallback', 'skipped', 'disabled', 'unavailable')),
  constraint admin_compat_obs_p5_count_check check (observation_count > 0 and unexplained_count between 0 and observation_count)
);

create table if not exists admin_governance_evidence_p5 (
  id bigint generated by default as identity primary key,
  evidence_type text not null,
  role_key text,
  outcome text not null,
  actor_hash text not null,
  evidence_at timestamptz not null default now(),
  expires_at timestamptz not null,
  evidence_digest text not null,
  note_code text,
  constraint admin_governance_evidence_p5_type_check check (evidence_type in ('owner_approval', 'backup_restore', 'acknowledgement')),
  constraint admin_governance_evidence_p5_role_check check (role_key is null or role_key in ('operations', 'data', 'security', 'backup')),
  constraint admin_governance_evidence_p5_outcome_check check (outcome in ('approved', 'successful', 'acknowledged')),
  constraint admin_governance_evidence_p5_actor_check check (actor_hash ~ '^[0-9a-f]{64}$'),
  constraint admin_governance_evidence_p5_digest_check check (evidence_digest ~ '^[0-9a-f]{64}$'),
  constraint admin_governance_evidence_p5_note_check check (note_code is null or note_code ~ '^[a-z][a-z0-9._-]{0,119}$'),
  constraint admin_governance_evidence_p5_expiry_check check (expires_at > evidence_at)
);

create table if not exists admin_retention_holds_p5 (
  id bigint generated by default as identity primary key,
  domain text not null,
  reason_code text not null,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  released_at timestamptz,
  evidence_digest text not null,
  constraint admin_retention_holds_p5_domain_check check (domain in ('all', 'commands', 'lifecycle', 'publication', 'observations', 'outbox')),
  constraint admin_retention_holds_p5_reason_check check (reason_code ~ '^[a-z][a-z0-9._-]{0,119}$'),
  constraint admin_retention_holds_p5_digest_check check (evidence_digest ~ '^[0-9a-f]{64}$'),
  constraint admin_retention_holds_p5_dates_check check (expires_at is null or expires_at > starts_at)
);

alter table admin_compatibility_observations_p5 enable row level security;
alter table admin_governance_evidence_p5 enable row level security;
alter table admin_retention_holds_p5 enable row level security;

create index if not exists admin_compat_obs_p5_window_idx
  on admin_compatibility_observations_p5 (bucket_started_at, authority, direction);
create index if not exists admin_governance_evidence_p5_current_idx
  on admin_governance_evidence_p5 (evidence_type, role_key, expires_at desc, evidence_at desc);
create index if not exists admin_retention_holds_p5_active_idx
  on admin_retention_holds_p5 (domain, starts_at, expires_at) where released_at is null;
create index if not exists ingestion_runs_source_started_p5_idx on ingestion_runs (source_key, started_at desc);
create index if not exists admin_command_runs_abort_p5_idx on admin_command_runs (abort_requested_at, finished_at) where abort_requested_at is not null;
create index if not exists admin_command_runs_retry_p5_idx on admin_command_runs (available_at, created_at) where status = 'retry_wait';
create index if not exists admin_command_attempts_finished_p5_idx on admin_command_attempts (finished_at, id) where status <> 'running';
create index if not exists admin_command_events_occurred_p5_idx on admin_command_events (occurred_at, id);
create index if not exists articles_lifecycle_review_age_p5_idx on articles (lifecycle_attention_raised_at, id) where lifecycle_attention_state in ('active', 'anomaly');
create index if not exists article_lifecycle_events_occurred_p5_idx on article_lifecycle_events_p2 (occurred_at, id);
create index if not exists article_publication_history_occurred_p5_idx on article_publication_history_p3 (occurred_at, id);
create index if not exists article_content_versions_created_p5_idx on article_content_versions_p3 (created_at, id);
create index if not exists article_cache_outbox_delivered_p5_idx on article_cache_outbox_p3 (delivered_at, id) where status = 'delivered';

create or replace function admin_p5_immutable_evidence()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  raise exception 'ADMIN_P5_IMMUTABLE_EVIDENCE';
end;
$$;

drop trigger if exists admin_governance_evidence_p5_immutable_trigger on admin_governance_evidence_p5;
create trigger admin_governance_evidence_p5_immutable_trigger before update or delete on admin_governance_evidence_p5
for each row execute function admin_p5_immutable_evidence();

create or replace function admin_record_compatibility_observation_p5(
  p_surface text,
  p_domain text,
  p_direction text,
  p_authority text,
  p_outcome text,
  p_count integer default 1
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_count integer := least(10000, greatest(1, coalesce(p_count, 1)));
begin
  if p_surface not in ('admin_command', 'article_lifecycle', 'article_publication', 'public_query', 'vector_search', 'admin_dashboard', 'admin_analytics')
    or p_domain not in ('queue', 'lifecycle', 'publication', 'projection', 'operations')
    or p_direction not in ('read', 'write')
    or p_authority not in ('legacy', 'new', 'fallback')
    or p_outcome not in ('selected', 'succeeded', 'failed', 'fallback', 'skipped', 'disabled', 'unavailable') then
    raise exception 'ADMIN_P5_INVALID_OBSERVATION';
  end if;

  insert into admin_compatibility_observations_p5 (
    bucket_started_at, surface, domain, direction, authority, outcome,
    observation_count, unexplained_count, first_observed_at, last_observed_at
  ) values (
    date_trunc('hour', v_now), p_surface, p_domain, p_direction, p_authority, p_outcome,
    v_count, case when p_authority in ('legacy', 'fallback') then v_count else 0 end, v_now, v_now
  )
  on conflict (bucket_started_at, surface, domain, direction, authority, outcome)
  do update set
    observation_count = least(9223372036854775807, admin_compatibility_observations_p5.observation_count + excluded.observation_count),
    unexplained_count = least(9223372036854775807, admin_compatibility_observations_p5.unexplained_count + excluded.unexplained_count),
    first_observed_at = least(admin_compatibility_observations_p5.first_observed_at, excluded.first_observed_at),
    last_observed_at = greatest(admin_compatibility_observations_p5.last_observed_at, excluded.last_observed_at);
end;
$$;

create or replace function admin_record_owner_approval_p5(
  p_role_key text,
  p_actor_hash text,
  p_evidence_digest text,
  p_expires_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
begin
  if p_role_key not in ('operations', 'data', 'security')
    or p_actor_hash !~ '^[0-9a-f]{64}$'
    or p_evidence_digest !~ '^[0-9a-f]{64}$'
    or p_expires_at <= now()
    or p_expires_at > now() + interval '180 days' then
    raise exception 'ADMIN_P5_INVALID_APPROVAL';
  end if;
  insert into admin_governance_evidence_p5 (
    evidence_type, role_key, outcome, actor_hash, expires_at, evidence_digest, note_code
  ) values ('owner_approval', p_role_key, 'approved', p_actor_hash, p_expires_at, p_evidence_digest, 'retirement.readiness')
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function admin_record_backup_restore_evidence_p5(
  p_actor_hash text,
  p_evidence_digest text,
  p_evidence_at timestamptz,
  p_expires_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
begin
  if p_actor_hash !~ '^[0-9a-f]{64}$'
    or p_evidence_digest !~ '^[0-9a-f]{64}$'
    or p_evidence_at > now() + interval '5 minutes'
    or p_evidence_at < now() - interval '90 days'
    or p_expires_at <= p_evidence_at
    or p_expires_at > p_evidence_at + interval '90 days' then
    raise exception 'ADMIN_P5_INVALID_BACKUP_EVIDENCE';
  end if;
  insert into admin_governance_evidence_p5 (
    evidence_type, role_key, outcome, actor_hash, evidence_at, expires_at, evidence_digest, note_code
  ) values ('backup_restore', 'backup', 'successful', p_actor_hash, p_evidence_at, p_expires_at, p_evidence_digest, 'backup.restore_rehearsal')
  returning id into v_id;
  return v_id;
end;
$$;

create or replace view admin_operational_health_core_p5
with (security_barrier = true)
as
with legacy_public as (
  select id from articles
  where status = 'summarized' and source_metadata #>> '{collection,publishable}' = 'true'
), explicit_public as (
  select id from public_article_projection_p3
), publication_identity as (
  select
    (select count(*) from legacy_public)::bigint as legacy_count,
    (select count(*) from explicit_public)::bigint as explicit_count,
    (select count(*) from (
      (select id from legacy_public except select id from explicit_public)
      union all
      (select id from explicit_public except select id from legacy_public)
    ) mismatch)::bigint as mismatch_count,
    (select md5(count(*)::text || ':' || coalesce(sum(hashtextextended(id::text, 0)::numeric), 0)::text) from legacy_public) as legacy_digest,
    (select md5(count(*)::text || ':' || coalesce(sum(hashtextextended(id::text, 0)::numeric), 0)::text) from explicit_public) as explicit_digest
), queue_states as (
  select coalesce(jsonb_object_agg(status, state_count), '{}'::jsonb) as states
  from (select status, count(*)::bigint as state_count from admin_command_runs group by status) grouped
)
select jsonb_build_object(
  'queue', jsonb_build_object(
    'states', (select states from queue_states),
    'oldestQueuedAgeSeconds', (select extract(epoch from now() - min(created_at))::bigint from admin_command_runs where status = 'queued'),
    'staleLeaseCount', (select count(*)::bigint from admin_command_attempts where status = 'running' and lease_expires_at < now()),
    'oldestHeartbeatAgeSeconds', (select extract(epoch from now() - min(heartbeat_at))::bigint from admin_command_attempts where status = 'running'),
    'abortPendingCount', (select count(*)::bigint from admin_command_runs where abort_requested_at is not null and finished_at is null),
    'oldestAbortAgeSeconds', (select extract(epoch from now() - min(abort_requested_at))::bigint from admin_command_runs where abort_requested_at is not null and finished_at is null),
    'retryWaitingCount', (select count(*)::bigint from admin_command_runs where status = 'retry_wait'),
    'oldestRetryAgeSeconds', (select extract(epoch from now() - min(created_at))::bigint from admin_command_runs where status = 'retry_wait')
  ),
  'lifecycle', jsonb_build_object(
    'backlogCount', (select count(*)::bigint from articles where lifecycle_attention_state in ('active', 'anomaly') or lifecycle_review_state = 'needs_review'),
    'oldestReviewAgeSeconds', (select extract(epoch from now() - min(coalesce(lifecycle_attention_raised_at, lifecycle_review_changed_at)))::bigint from articles where lifecycle_attention_state in ('active', 'anomaly') or lifecycle_review_state = 'needs_review'),
    'unresolvedAnomalyCount', (select count(*)::bigint from article_lifecycle_anomalies_p2 where resolved_at is null)
  ),
  'publication', jsonb_build_object(
    'legacyPublicCount', (select legacy_count from publication_identity),
    'explicitPublicCount', (select explicit_count from publication_identity),
    'parityMismatchCount', (select mismatch_count from publication_identity),
    'quarantineCount', (select count(*)::bigint from article_publication_quarantine_p3),
    'legacyIdentityDigest', (select legacy_digest from publication_identity),
    'explicitIdentityDigest', (select explicit_digest from publication_identity)
  ),
  'outbox', jsonb_build_object(
    'pendingCount', (select count(*)::bigint from article_cache_outbox_p3 where status = 'pending'),
    'processingCount', (select count(*)::bigint from article_cache_outbox_p3 where status = 'processing'),
    'deadLetterCount', (select count(*)::bigint from article_cache_outbox_p3 where status = 'dead_letter'),
    'oldestUndeliveredAgeSeconds', (select extract(epoch from now() - min(created_at))::bigint from article_cache_outbox_p3 where status in ('pending', 'processing'))
  ),
  'inFlight', jsonb_build_object(
    'legacyCount', (select count(*)::bigint from admin_jobs where status in ('queued', 'running', 'cancel_requested')),
    'newCount', (select count(*)::bigint from admin_command_runs where status in ('queued', 'running', 'retry_wait')),
    'conflict', (select exists(select 1 from admin_jobs where status in ('queued', 'running', 'cancel_requested'))) and (select exists(select 1 from admin_command_runs where status in ('queued', 'running', 'retry_wait')))
  )
) as evidence;

create or replace function admin_retention_plan_p5(
  p_command_before timestamptz,
  p_lifecycle_before timestamptz,
  p_publication_before timestamptz,
  p_observation_before timestamptz,
  p_delivered_outbox_before timestamptz,
  p_dead_letter_outbox_before timestamptz
)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'commandAttemptsDue', (select count(*)::bigint from admin_command_attempts where status <> 'running' and finished_at < p_command_before),
    'commandEventsDue', (select count(*)::bigint from admin_command_events e join admin_command_runs r on r.id = e.run_id where r.finished_at < p_command_before),
    'lifecycleEventsDue', (select count(*)::bigint from article_lifecycle_events_p2 where occurred_at < p_lifecycle_before),
    'publicationHistoryDue', (select count(*)::bigint from article_publication_history_p3 where occurred_at < p_publication_before),
    'contentVersionsDue', (select count(*)::bigint from article_content_versions_p3 where created_at < p_publication_before),
    'compatibilityObservationsDue', (select count(*)::bigint from admin_compatibility_observations_p5 where bucket_started_at < p_observation_before),
    'deliveredOutboxDue', (select count(*)::bigint from article_cache_outbox_p3 where status = 'delivered' and delivered_at < p_delivered_outbox_before),
    'deadLetterOutboxDue', (select count(*)::bigint from article_cache_outbox_p3 where status = 'dead_letter' and dead_lettered_at < p_dead_letter_outbox_before),
    'legalHoldActive', exists(select 1 from admin_retention_holds_p5 where released_at is null and starts_at <= now() and (expires_at is null or expires_at > now())),
    'recommendations', jsonb_build_object(
      'commands', 'archive_partition',
      'lifecycle', 'retain_immutable_archive',
      'publication', 'retain_immutable_authority',
      'observations', 'batch_delete_allowed',
      'deliveredOutbox', 'batch_delete_allowed',
      'deadLetterOutbox', 'archive_only'
    )
  );
$$;

create or replace function admin_operational_health_p5(
  p_observation_start timestamptz,
  p_observation_end timestamptz,
  p_command_before timestamptz,
  p_lifecycle_before timestamptz,
  p_publication_before timestamptz,
  p_observation_before timestamptz,
  p_delivered_outbox_before timestamptz,
  p_dead_letter_outbox_before timestamptz
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_core jsonb;
  v_compat jsonb;
  v_sources jsonb;
  v_governance jsonb;
  v_retention jsonb;
begin
  if p_observation_start is null or p_observation_end is null
    or p_observation_start >= p_observation_end
    or p_observation_end > now() + interval '5 minutes'
    or p_observation_end - p_observation_start > interval '90 days' then
    raise exception 'ADMIN_P5_INVALID_WINDOW';
  end if;

  select evidence into v_core from admin_operational_health_core_p5;
  select jsonb_build_object(
    'totalCount', coalesce(sum(observation_count), 0)::bigint,
    'legacyReadCount', coalesce(sum(observation_count) filter (where authority = 'legacy' and direction = 'read'), 0)::bigint,
    'legacyWriteCount', coalesce(sum(observation_count) filter (where authority = 'legacy' and direction = 'write'), 0)::bigint,
    'newReadCount', coalesce(sum(observation_count) filter (where authority = 'new' and direction = 'read'), 0)::bigint,
    'newWriteCount', coalesce(sum(observation_count) filter (where authority = 'new' and direction = 'write'), 0)::bigint,
    'fallbackCount', coalesce(sum(observation_count) filter (where authority = 'fallback'), 0)::bigint,
    'unexplainedLegacyCount', coalesce(sum(unexplained_count), 0)::bigint,
    'firstObservedAt', min(first_observed_at),
    'lastObservedAt', max(last_observed_at),
    'bucketCount', count(*)::bigint
  ) into v_compat
  from admin_compatibility_observations_p5
  where bucket_started_at >= date_trunc('hour', p_observation_start)
    and bucket_started_at <= date_trunc('hour', p_observation_end);

  select coalesce(jsonb_agg(jsonb_build_object(
    'sourceKey', s.source_key,
    'active', s.is_active,
    'latestRunAt', latest.started_at,
    'freshnessAgeSeconds', case when latest.started_at is null then null else extract(epoch from now() - latest.started_at)::bigint end
  ) order by s.source_key), '[]'::jsonb) into v_sources
  from sources s
  left join lateral (
    select r.started_at from ingestion_runs r where r.source_key = s.source_key order by r.started_at desc limit 1
  ) latest on true;

  select jsonb_build_object(
    'backupRestoreAt', (select evidence_at from admin_governance_evidence_p5 where evidence_type = 'backup_restore' and outcome = 'successful' order by evidence_at desc limit 1),
    'backupRestoreExpiresAt', (select expires_at from admin_governance_evidence_p5 where evidence_type = 'backup_restore' and outcome = 'successful' order by evidence_at desc limit 1),
    'approvedRoles', coalesce((select jsonb_agg(role_key order by role_key) from (
      select distinct on (role_key) role_key from admin_governance_evidence_p5
      where evidence_type = 'owner_approval' and outcome = 'approved' and expires_at > now()
      order by role_key, evidence_at desc
    ) approvals), '[]'::jsonb)
  ) into v_governance;

  v_retention := admin_retention_plan_p5(p_command_before, p_lifecycle_before, p_publication_before, p_observation_before, p_delivered_outbox_before, p_dead_letter_outbox_before);
  return jsonb_build_object(
    'schemaVersion', 1,
    'generatedAt', now(),
    'available', true,
    'observationWindow', jsonb_build_object('start', p_observation_start, 'end', p_observation_end),
    'queue', v_core->'queue',
    'lifecycle', v_core->'lifecycle',
    'publication', v_core->'publication',
    'outbox', v_core->'outbox',
    'sources', v_sources,
    'compatibility', v_compat,
    'inFlight', v_core->'inFlight',
    'governance', v_governance,
    'retention', v_retention - 'recommendations'
  );
end;
$$;

create or replace function admin_apply_retention_p5(
  p_observation_before timestamptz,
  p_delivered_outbox_before timestamptz,
  p_batch_size integer,
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_batch integer := least(500, greatest(1, coalesce(p_batch_size, 250)));
  v_observations integer := 0;
  v_outbox integer := 0;
begin
  if p_confirmation <> 'APPLY P5 RETENTION' then
    raise exception 'ADMIN_P5_CONFIRMATION_REQUIRED';
  end if;
  if p_observation_before > now() - interval '180 days' or p_delivered_outbox_before > now() - interval '90 days' then
    raise exception 'ADMIN_P5_RETENTION_MINIMUM';
  end if;
  if exists(select 1 from admin_retention_holds_p5 where released_at is null and starts_at <= now() and (expires_at is null or expires_at > now()) and domain in ('all', 'observations', 'outbox')) then
    raise exception 'ADMIN_P5_LEGAL_HOLD';
  end if;

  with target as (
    select ctid from admin_compatibility_observations_p5 where bucket_started_at < p_observation_before order by bucket_started_at limit v_batch
  ), deleted as (
    delete from admin_compatibility_observations_p5 where ctid in (select ctid from target) returning 1
  ) select count(*) into v_observations from deleted;

  with target as (
    select id from article_cache_outbox_p3 where status = 'delivered' and delivered_at < p_delivered_outbox_before order by delivered_at, id limit v_batch
  ), deleted as (
    delete from article_cache_outbox_p3 where id in (select id from target) and status = 'delivered' returning 1
  ) select count(*) into v_outbox from deleted;

  return jsonb_build_object(
    'compatibilityObservationsDeleted', v_observations,
    'deliveredOutboxDeleted', v_outbox,
    'batchSize', v_batch,
    'authoritativeHistoryDeleted', 0,
    'deadLettersDeleted', 0
  );
end;
$$;

revoke all on table admin_compatibility_observations_p5, admin_governance_evidence_p5, admin_retention_holds_p5 from public;
revoke all on admin_operational_health_core_p5 from public;
revoke all on function admin_record_compatibility_observation_p5(text, text, text, text, text, integer) from public;
revoke all on function admin_record_owner_approval_p5(text, text, text, timestamptz) from public;
revoke all on function admin_record_backup_restore_evidence_p5(text, text, timestamptz, timestamptz) from public;
revoke all on function admin_p5_immutable_evidence() from public;
revoke all on function admin_retention_plan_p5(timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz) from public;
revoke all on function admin_operational_health_p5(timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz) from public;
revoke all on function admin_apply_retention_p5(timestamptz, timestamptz, integer, text) from public;

do $$
begin
  if exists(select 1 from pg_roles where rolname = 'anon') then
    revoke all on table admin_compatibility_observations_p5, admin_governance_evidence_p5, admin_retention_holds_p5 from anon;
    revoke all on admin_operational_health_core_p5 from anon;
  end if;
  if exists(select 1 from pg_roles where rolname = 'authenticated') then
    revoke all on table admin_compatibility_observations_p5, admin_governance_evidence_p5, admin_retention_holds_p5 from authenticated;
    revoke all on admin_operational_health_core_p5 from authenticated;
  end if;
  if exists(select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function admin_record_compatibility_observation_p5(text, text, text, text, text, integer) to service_role;
    grant execute on function admin_record_owner_approval_p5(text, text, text, timestamptz) to service_role;
    grant execute on function admin_record_backup_restore_evidence_p5(text, text, timestamptz, timestamptz) to service_role;
    grant execute on function admin_retention_plan_p5(timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz) to service_role;
    grant execute on function admin_operational_health_p5(timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz, timestamptz) to service_role;
    grant execute on function admin_apply_retention_p5(timestamptz, timestamptz, integer, text) to service_role;
  end if;
end;
$$;
